const currentYear = new Date().getFullYear();

export const DATE_WITH_YEAR = 'May 23, 2026';

export const DATE_NO_YEAR = "05-23";

export const DATE_NO_YEAR_WITH_CURRENT_YEAR = DATE_NO_YEAR
  ? `${currentYear}-${DATE_NO_YEAR}`
  : "";

export const appVersion = { entry: "Version", version: "0.1.0" };

export const PRICE = "3,999";

export const CLASS_TOPICS = {
  CBSE: {
    "Class 1": {
      Maths: {
        topics: [
          "Numbers 1-100",
          "Addition",
          "Subtraction",
          "Shapes",
          "Patterns",
        ],
      },
      EVS: {
        topics: ["Myself", "Family", "Plants", "Animals", "Food", "Water"],
      },
      English: { topics: ["Alphabet", "Basic Words", "Simple Sentences"] },
      Hindi: { topics: ["Varnmala", "Basic Words", "Simple Sentences"] },
      Computer: { topics: ["Computer Basics", "Uses of Computer"] },
    },
    "Class 2": {
      Maths: {
        topics: [
          "Numbers up to 1000",
          "Addition",
          "Subtraction",
          "Multiplication Basics",
        ],
      },
      EVS: {
        topics: ["Plants", "Animals", "Human Body", "Transport", "Safety"],
      },
      English: { topics: ["Nouns", "Pronouns", "Verbs"] },
      Hindi: { topics: ["Sangya", "Sarvanaam", "Kriya"] },
      Computer: { topics: ["Parts of Computer", "Input Devices"] },
    },
    "Class 3": {
      Maths: {
        topics: ["Place Value", "Multiplication", "Division", "Fractions"],
      },
      EVS: { topics: ["Living & Non-living", "Food", "Water", "Shelter"] },
      English: { topics: ["Parts of Speech", "Basic Tenses"] },
      Hindi: { topics: ["Ling", "Vachan", "Kriya"] },
      Computer: { topics: ["Keyboard", "Basic Software"] },
    },
    "Class 4": {
      Maths: { topics: ["Large Numbers", "Fractions", "Decimals", "Geometry"] },
      EVS: {
        topics: ["Plants", "Animals", "Natural Resources", "States of India"],
      },
      English: { topics: ["Tenses", "Adjectives", "Prepositions"] },
      Hindi: { topics: ["Sangya", "Sarvanaam", "Kaal"] },
      Computer: { topics: ["MS Paint", "Basic Applications"] },
    },
    "Class 5": {
      Maths: {
        topics: ["Decimals", "Fractions", "Measurement", "Data Handling"],
      },
      EVS: {
        topics: ["Human Body", "Energy", "Environment", "Indian Geography"],
      },
      English: { topics: ["Tenses", "Articles", "Conjunctions"] },
      Hindi: { topics: ["Kaal", "Vakya", "Muhavare"] },
      Computer: { topics: ["MS Word", "Internet Basics"] },
    },
    "Class 6": {
      Maths: {
        topics: ["Integers", "Fractions", "Ratio", "Algebra", "Mensuration"],
      },
      Science: {
        topics: ["Food", "Materials", "Motion", "Light", "Electricity"],
      },
      SST: { topics: ["Ancient History", "Geography", "Civics"] },
      English: { topics: ["Grammar", "Writing Skills"] },
      Hindi: { topics: ["Sandhi", "Samas", "Kaal"] },
      Computer: { topics: ["MS Office", "Internet"] },
    },
    "Class 7": {
      Maths: { topics: ["Algebra", "Ratio", "Geometry", "Mensuration"] },
      Science: { topics: ["Heat", "Acids & Bases", "Motion", "Electricity"] },
      SST: { topics: ["Medieval History", "Environment", "Democracy"] },
      English: { topics: ["Tenses", "Voice", "Writing Skills"] },
      Hindi: { topics: ["Samas", "Kaal", "Vakya Bhed"] },
      Computer: { topics: ["Spreadsheets", "Internet Tools"] },
    },
    "Class 8": {
      Maths: {
        topics: ["Linear Equations", "Squares", "Mensuration", "Graphs"],
      },
      Science: {
        topics: ["Force", "Light", "Sound", "Microorganisms", "Friction"],
      },
      SST: { topics: ["Modern History", "Resources", "Constitution"] },
      English: { topics: ["Grammar", "Writing", "Literature"] },
      Hindi: { topics: ["Sandhi", "Samas", "Muhavare"] },
      Computer: { topics: ["Basics of Programming", "Internet"] },
    },
  },

  ICSE: {
    "Class 1": {
      Maths: { topics: ["Numbers", "Addition", "Subtraction", "Shapes"] },
      EVS: { topics: ["Myself", "Plants", "Animals", "Food"] },
      English: { topics: ["Alphabet", "Words", "Sentences"] },
      Hindi: { topics: ["Varnmala", "Words"] },
      Computer: { topics: ["Computer Basics"] },
    },
    "Class 2": {
      Maths: {
        topics: ["Numbers", "Addition", "Subtraction", "Multiplication"],
      },
      EVS: { topics: ["Plants", "Animals", "Transport", "Safety"] },
      English: { topics: ["Nouns", "Verbs", "Pronouns"] },
      Hindi: { topics: ["Sangya", "Kriya", "Sarvanaam"] },
      Computer: { topics: ["Parts of Computer"] },
    },
    "Class 3": {
      Maths: { topics: ["Place Value", "Fractions", "Measurement"] },
      EVS: { topics: ["Living & Non-living", "Food", "Water"] },
      English: { topics: ["Grammar Basics", "Tenses"] },
      Hindi: { topics: ["Ling", "Vachan"] },
      Computer: { topics: ["Hardware", "Software"] },
    },
    "Class 4": {
      Maths: { topics: ["Fractions", "Decimals", "Geometry"] },
      Science: { topics: ["Plants", "Animals", "Matter"] },
      SST: { topics: ["Geography", "History"] },
      English: { topics: ["Tenses", "Adjectives"] },
      Hindi: { topics: ["Kaal", "Vakya"] },
      Computer: { topics: ["MS Paint"] },
    },
    "Class 5": {
      Maths: { topics: ["Fractions", "Geometry", "Measurement"] },
      Science: { topics: ["Human Body", "Energy", "Plants"] },
      SST: { topics: ["History", "Geography", "Civics"] },
      English: { topics: ["Tenses", "Articles"] },
      Hindi: { topics: ["Kaal", "Muhavare"] },
      Computer: { topics: ["MS Word"] },
    },
    "Class 6": {
      Maths: { topics: ["Integers", "Algebra", "Ratio"] },
      Science: { topics: ["Physics", "Chemistry", "Biology"] },
      SST: { topics: ["History", "Civics", "Geography"] },
      English: { topics: ["Grammar", "Writing"] },
      Hindi: { topics: ["Sandhi", "Samas"] },
      Computer: { topics: ["MS Office"] },
    },
    "Class 7": {
      Maths: { topics: ["Algebra", "Mensuration", "Geometry"] },
      Science: { topics: ["Heat", "Acids", "Motion"] },
      SST: { topics: ["Medieval History", "Civics"] },
      English: { topics: ["Tenses", "Voice"] },
      Hindi: { topics: ["Samas", "Vakya"] },
      Computer: { topics: ["Spreadsheets"] },
    },
    "Class 8": {
      Maths: { topics: ["Linear Equations", "Graphs", "Mensuration"] },
      Science: { topics: ["Physics", "Chemistry", "Biology"] },
      SST: { topics: ["Modern History", "Geography"] },
      English: { topics: ["Grammar", "Writing"] },
      Hindi: { topics: ["Sandhi", "Muhavare"] },
      Computer: { topics: ["Programming Basics"] },
    },
  },

  StateBoard: {
    "Class 1": {
      Maths: { topics: ["Numbers", "Addition", "Shapes"] },
      EVS: { topics: ["Family", "Plants", "Animals"] },
      English: { topics: ["Alphabet", "Words"] },
      Hindi: { topics: ["Varnmala"] },
    },
    "Class 2": {
      Maths: { topics: ["Numbers", "Addition", "Subtraction"] },
      EVS: { topics: ["Plants", "Animals", "Transport"] },
      English: { topics: ["Words", "Sentences"] },
      Hindi: { topics: ["Words", "Simple Sentences"] },
    },
    "Class 3": {
      Maths: { topics: ["Multiplication", "Division", "Fractions"] },
      EVS: { topics: ["Food", "Water", "Shelter"] },
      English: { topics: ["Grammar Basics"] },
      Hindi: { topics: ["Ling", "Vachan"] },
      Computer: { topics: ["Basic Computer"] },
    },
    "Class 4": {
      Maths: { topics: ["Fractions", "Decimals", "Geometry"] },
      Science: { topics: ["Plants", "Animals", "Matter"] },
      SST: { topics: ["Geography", "History"] },
      English: { topics: ["Tenses"] },
      Hindi: { topics: ["Kaal"] },
    },
    "Class 5": {
      Maths: { topics: ["Fractions", "Measurement", "Data Handling"] },
      Science: { topics: ["Human Body", "Energy"] },
      SST: { topics: ["History", "Geography"] },
      English: { topics: ["Tenses", "Articles"] },
      Hindi: { topics: ["Vakya", "Muhavare"] },
    },
    "Class 6": {
      Maths: { topics: ["Integers", "Algebra", "Ratio"] },
      Science: { topics: ["Food", "Light", "Materials"] },
      SST: { topics: ["History", "Civics", "Geography"] },
      English: { topics: ["Grammar", "Writing"] },
      Hindi: { topics: ["Sandhi"] },
    },
    "Class 7": {
      Maths: { topics: ["Algebra", "Geometry", "Mensuration"] },
      Science: { topics: ["Heat", "Acids", "Motion"] },
      SST: { topics: ["History", "Environment"] },
      English: { topics: ["Tenses", "Voice"] },
      Hindi: { topics: ["Samas"] },
    },
    "Class 8": {
      Maths: { topics: ["Algebra", "Mensuration", "Linear Equations"] },
      Science: { topics: ["Physics", "Chemistry", "Biology"] },
      SST: { topics: ["Modern History", "Civics"] },
      English: { topics: ["Grammar", "Writing"] },
      Hindi: { topics: ["Sandhi", "Muhavare"] },
    },
  },

  NCERT: {
    "Class 1": {
      Maths: {
        topics: [
          "Finding the Furry Cat",
          "What is Long? What is Round?",
          "Mango Treat",
          "Making 10",
          "How Many? (Addition and Subtraction of Single Digit Numbers)",
          "Vegetable Farm (Addition and Subtraction up to 20)",
          "Lina’s Family (Measurement)",
          "Fun with Numbers (Numbers 21 to 99)",
          "Utsav (Patterns)",
          "How do I Spend my Day? (Time)",
          "How Many Times? (Multiplication)",
          "How Much Can We Spend? (Money)",
          "So Many Toys (Data Handling)",
        ],
      },
      English: {
        topics: [
          "Two Little Hands",
          "Greetings",
          "Picture Time",
          "The Cap-seller and the Monkeys",
          "A Farm",
          "Fun with Pictures",
          "The Food we Eat",
          "The Four Seasons",
          "Anandi’s Rainbow",
        ],
      },
      Hindi: {
        topics: [
          "Meena ka parivaar",
          "Chanda mama door ke",
          "Dada-dadi",
          "Reena ka din",
          "Rani bhi",
          "Murgabola kukdu-koo",
          "Mithai",
          "Teen saathi",
          "Wah, mere ghode",
          "Khatre mein saanp",
          "Kabri jhabri bakri",
          "Aloo ki sada",
          "Jhoolam-jhooli",
          "Bhutte",
          "Phooli roti",
          "Mela",
          "Barkha aur Megha",
          "Holi",
          "Janmdin par ped lagao",
          "Hawa",
          "Kitni pyari hai ye duniya",
          "Chaand ka bachcha",
        ],
      },
    },
    "Class 2": {
      Maths: {
        topics: [
          "A Day at the Beach (Counting in Groups)",
          "Shapes Around Us (3D Shapes)",
          "Fun with Numbers (Numbers 1 to 100)",
          "Shadow Story (Togalu) (2D Shapes)",
          "Playing with Lines (Orientations of a line)",
          "Decoration for Festival (Addition and Subtraction)",
          "Rani’s Gift (Measurement)",
          "Grouping and Sharing (Multiplication and Division)",
          "Which Season is it? (Measurement of Time)",
          "Fun at the Fair (Money)",
          "Data Handling",
        ],
      },
      English: {
        topics: [
          "My Bicycle",
          "Picture Reading",
          "It is Fun",
          "Seeing without Seeing ",
          "Come Back Soon",
          "Between Home and School",
          "This is My Town",
          "A Show of Clouds",
          "My Name",
          "The Crow",
          "The Smart Monkey",
          "Little Drops of Water",
          "We are all Indians",
        ],
      },
      Hindi: {
        topics: [
          "Neema ki Dadi",
          "Ghar",
          "Mala ki Chandi ki Payal",
          "Maa",
          "Thath aur Main",
          "Cheenta",
          "Tillu Ji",
          "Natkhat Diwakar",
          "Teen Dost",
          "Duniya Rang-Birangi",
          "Kaun",
          "Baingani Jojo",
          "Tosiya ka Sapna Talaab",
          "Beej",
          "Kisaan",
          "Mooli",
          "Barsaat aur Mendhak",
          "Utho Utho",
          "Sher aur Chuhe ki Dosti",
          "Out",
          "Khel Sandhya",
          "Chhupan-Chhupai",
          "Haathi Cycle Chala Raha Tha",
          "Daro Mat!",
          "Chaar Dishaayein",
          "Chanda Mama",
          "Gire Taal Mein Chanda Mama",
          "Sabse Bada Chhata",
          "Baadal",
          "Phir Phurr!",
        ],
      },
    },
    "Class 3": {
      Maths: {
        topics: [
          "What’s in a Name?",
          "Toy Joy",
          "Double Century",
          "Vacation with My Nani Maa",
          "Fun with Shapes",
          "House of Hundreds– I",
          "Raksha Bandhan",
          "Fair Share",
          "House of Hundreds– II",
          "Fun at Class Party!",
          "Filling and Lifting",
          "Give and Take",
          "Time Goes On",
          "The Surajkund Fair",
          "Learning Material Sheets",
        ],
      },
      Arts: {
        topics: [
          "Our National Anthem",
          "Feel the Rhythm ta ka ta ki Ta",
          "Travel Around",
          "Musical Instruments",
          "Celebratory Notes Let us Dance",
          "Dance for Joy",
          "I Play and Dance",
          "Dance with Nature Explore",
          "Imagine",
          "Let’s Create",
          "Look Around",
          "Activities",
          "Integrating All Art Forms",
          "Objects in Art",
          "Plants in Art",
          "Animals in Art",
          "People Around Us",
          "Festivals, Occasions, and Celebrations",
        ],
      },
      English: {
        topics: [
          "Colours",
          "Badal and Moti",
          "Best Friends Out in the Garden",
          "Talking Toys",
          "Paper Boats The Big Laddoo",
          "Thank God",
          "Madhu’s Wish Night",
          "Chanda Mama Counts the Stars",
          "Chandrayaan",
        ],
      },
      Hindi: {
        topics: [
          "Seekho",
          "Cheenti",
          "Cheenti aur haathi ki chhupan-chhupai",
          "Kitne pair?",
          "Dost ke joote",
          "Baya hamari chidiya rani!",
          "Aam ka ped",
          "Birbal ki khichdi",
          "Mila ko pata",
          "Chatur gidad",
          "Prakriti parv (Phooldei)",
          "Sano bhai gup-gup",
          "Rassakashi",
          "Traffic jam",
          "Ek jaadui pitara",
          "Apna-apna kaam",
          "Pedon ki amma 'Timkka'",
          "Kisaan ki hoshiyari",
          "Bharat",
          "Chandrayaan (samvaad)",
          "Bolne wali maand",
          "Hum anek kintu ek",
          "Hind desh ke nivasi",
        ],
      },
      "Physical Education": {
        topics: [
          "Throwing and Catching",
          "Kicking and Receiving",
          "Strike the Ball",
          "Little Steps",
          "Local and Traditional Games",
          "Yoga for Daily Life",
          "Yogic Practices (Yoga Sadhana)",
        ],
      },
      "World around us": {
        topics: [
          "Family and Friends",
          "Going to the Mela",
          "Celebrating Festivals",
          "Life Around Us Getting to Know Plants",
          "Plants and Animals Live Together",
          "Living in Harmony",
          "Gifts of Nature Water— A Precious Gift",
          "Food We Eat",
          "Staying Healthy and Happy",
          "Things Around Us This World of Things",
          "Making Things",
          "Taking Charge of Waste",
        ],
      },
    },
    "Class 4": {
      Maths: {
        topics: [
          "Shapes Around Us",
          "Hide and Seek",
          "Pattern Around Us",
          "Thousands Around Us",
          "Sharing and Measuring",
          "Measuring Length",
          "The Cleanest Village",
          "Weigh it, Pour it",
          "Equal Groups",
          "Elephants, Tigers, and Leopards",
          "Fun with Symmetry",
          "Ticking Clocks and Turning Calendar",
          "The Transport Museum",
          "Data Handling",
        ],
      },
      Arts: {
        topics: [
          "Arrangements of Objects",
          "Textures in Nature",
          "Aqua World",
          "People in Action",
          "THEATRE Explore!",
          "Imagine",
          "Let’s Create",
          "Look Around Sing and Play",
          "Making Music",
          "Songs and Stories",
          "Think, Feel, Create",
          "Sounds and Instruments",
          "DANCE My Body in Dance",
          "My Dance Tells Stories",
          "Creating My Dance",
          "Emotion and Expression in Dance",
          "Dances Around Me",
        ],
      },
      "World around us": {
        topics: [
          "Living Together",
          "Exploring Our Neighbourhood",
          "Nature Trail",
          "Growing up with Nature",
          "Food for Health",
          "Happy and Healthy Living",
          "How Things Work",
          "How Things are Made",
          "Different Lands, Different Lives",
          "Our Sky",
        ],
      },
      English: {
        topics: [
          "Together We Can",
          "The Tinkling Bells",
          "Be Smart, Be Safe",
          "One Thing at a Time",
          "The Old Stag",
          "Braille",
          "Fit Body, Fit Mind, Fit Nation",
          "The Lagori Champions",
          "Hekko",
          "The Swing",
          "A Journey to the Magical Mountains",
          "Maheshwar",
        ],
      },
      Hindi: {
        topics: [
          "Chidiya ka geet",
          "Mati ki udaan",
          "Bagiche ka ghongha",
          "Neem",
          "Bhaanti-bhaanti ki pattiyan",
          "Hamara aahar",
          "Aasman gira",
          "Cherapunji ke mehmaan",
          "Jaipur se patra",
          "Golgappa",
          "Nakli heere",
          "Hawa aur dhool",
          "Onam ke rang",
          "Mithaiyon ka sammelan",
          "Jalebi",
          "Camera",
          "Sun, imli ke dane sun!",
          "Thahake",
          "Kavita ka kamaal",
          "Shatranj mein maat",
          "Hamara Aditya",
          "Hum sab saman ek upvan",
        ],
      },
    },

    "Class 5": {
      Arts: {
        topics: [
          "Objects on the Move",
          "Peeping Out of the Window",
          "Picturing Stories",
          "Imaginary Beings",
          "Spreading the Message",
          "Create a Scene",
          "Stitch it for a Story",
          "Time, Team, Technique",
          "View and Review",
          "Sing and Play",
          "Music Around Me",
          "Sounds and Instruments",
          "Building Blocks",
          "Ideas and Inspiration",
          "My Everyday Activities in Modes of Dance",
          "Dancing with Rhythm and Tempos",
          "Dances of My Nation",
          "My Dance Expresses Emotions and Narrates Stories",
          "My Dance and Your Dance",
        ],
      },
      English: {
        topics: [
          "Papa’s Spectacles",
          "Gone with the Scooter",
          "The Rainbow",
          "The Wise Parrot",
          "The Frog",
          "What a Tank!",
          "Gilli Danda",
          "The Decision of the Panchayat",
          "Vocation",
          "Glass Bangles",
        ],
      },
      Maths: {
        topics: [
          "We the Travellers—I",
          "Fractions",
          "Angles as Turns",
          "We the Travellers—II",
          "Far and Near",
          "The Dairy Farm",
          "Shapes and Patterns",
          "Weight and Capacity",
          "Coconut Farm",
          "Symmetrical Designs",
          "Grandmother’s Quilt",
          "Racing Seconds",
          "Animal Jumps",
          "Maps and Locations",
          "Data Through Pictures",
        ],
      },
      "Physical Education": {
        topics: [
          "Throwing and Catching",
          "Kicking and Receiving",
          "Strike the Object",
          "Little Steps",
          "Local and Traditional Games",
          "Yoga for Daily Life",
          "Yoga Sadhana",
        ],
      },
      "World Around Us": {
        topics: [
          "Water—The Essence of Life",
          "Journey of a River",
          "The Mystery of Food",
          "Our School—A Happy Place",
          "Our Vibrant Country",
          "Some Unique Places",
          "Energy—How Things Work",
          "Clothes—How Things are Made",
          "Rhythms of Nature",
          "Earth—Our Shared Home",
        ],
      },
      hindi: {
        topics: [
          "Kiran",
          "Ped ka jadoo",
          "Nyay ki kusal",
          "Chand ka kurta",
          "Jago pyare",
          "Saanket",
          "Holi aai, Holi aai",
          "Saduriyan",
          "Haathi aur cheenti",
          "Chatur chitrakar",
          "Do mendhakon ki yatra",
          "Mera bachpan",
          "Kaziranga Rashtriya Udyan ki yatra",
          "Ghumo-dekho",
          "Nyay",
          "Teen machhliyan",
          "Humare ye kalam mandir",
          "Ganga ki kahani",
          "Gaganyaan",
        ],
      },
    },

    "Class 6": {
      Arts: {
        topics: [
          "Objects and Still Life",
          "Changing the Typical Picture",
          "Portraying People",
          "Paper Crafts",
          "Seals to Prints",
          "Music and your Emotions",
          "Musical Instruments",
          "Taal or Talam and Raga or Ragam in Indian Music",
          "Melodies of Diversity",
          "Songwriting",
          "Music and Society",
          "My Body in Motion",
          "Breaking Barriers with Dance",
          "Harmony in Motion",
          "Dances of Our Land",
          "Emotions Unveiled",
          "Let’s Design",
          "In the Company of Theatre",
          "Stories of Shadows and Strings — Puppetry",
          "The Grand Finale",
          "Integration of All Art Forms",
        ],
      },
      English: {
        topics: [
          "A Bottle of Dew",
          "The Raven and the Fox",
          "Rama to the Rescue",
          "The Unlikely Best Friends",
          "A Friend’s Prayer",
          "The Chair",
          "Neem Baba",
          "What a Bird Thought",
          "Spices that Heal Us",
          "Change of Heart",
          "The Winner",
          "Yoga—A Way of Life",
          "Hamara Bharat—Incredible India!",
          "The Kites",
          "Ila Sachani: Embroidering Dreams with her Feet",
          "National War Memorial",
        ],
      },
      Maths: {
        topics: [
          "Patterns in Mathematics",
          "Lines and Angles",
          "Number Play",
          "Data Handling and Presentation",
          "Prime Time",
          "Perimeter and Area",
          "Fractions",
          "Playing with Constructions",
          "Symmetry",
          "The Other Side of Zero",
        ],
      },
      "Physical Education": {
        topics: [
          "Ice Water",
          "Seven Stones",
          "Aerobic Exercises",
          "Follow Me",
          "Number Game",
          "Hula Hoop Jump",
          "Obstacle Race",
          "Balancing Act",
          "Shivam Says",
          "Collaborate and Conquer",
          "Grab the Ball",
          "Push-up Position and Pass the Ball",
          "Tic-Tac-Toe Dribble Relay",
          "Crocodile Race",
          "Head, Shoulder, Knee and Ball",
          "Sitting",
          "Chasing",
          "Giving Kho",
          "Running on a Straight Line",
          "Dodging",
          "Zig-Zag Running",
          "Pole Turn",
          "Covering Chase",
          "Chain",
          "Fake Kho",
          "Pole Dive",
          "Toe Tapping",
          "3-2-3 Chain",
          "Passing",
          "Catching",
          "10-pass",
          "Dribbling",
          "Obstacle Dribbling",
          "Shoot the Ball",
          "Dodge Ball",
          "Dribble and Shoot",
          "Pass and Shoot",
          "Shootout Tournament",
          "Goalkeeper’s Defensive Skills",
          "Blocking",
          "Assimilation",
          "Yoga for Daily Life",
          "Preparing for Yogic Practices",
          "Āsanas",
          "Prānāyāma",
          "Dhārana, Dhyāna, and Samādhi",
          "Krīdā Yoga",
        ],
      },
      Science: {
        topics: [
          "The Wonderful World of Science",
          "Diversity in the Living World",
          "Mindful Eating: A Path to a Healthy Body",
          "Exploring Magnets",
          "Measurement of Length and Motion",
          "Materials Around Us",
          "Temperature and its Measurement",
          "A Journey through States of Water",
          "Methods of Separation in Everyday Life",
          "Living Creatures: Exploring their Characteristics",
          "Nature’s Treasures",
          "Beyond Earth",
        ],
      },
      "Social Science": {
        topics: [
          "Locating Places on the Earth",
          "Oceans and Continents",
          "Landforms and Life",
          "Timeline and Sources of History",
          "India, That Is Bharat",
          "The Beginnings of Indian Civilisation",
          "India's Cultural Roots",
          "Unity in Diversity, or Many in the One",
          "Family and Community",
          "Grassroots Democracy — Governance",
          "Grassroots Democracy — Local Government in Rural Areas",
          "Grassroots Democracy — Local Government in Urban Areas",
          "The Value of Work",
          "Economic Activities Around Us",
        ],
      },
      "Vocational Education": {
        topics: [
          "School Kitchen Garden",
          "Biodiversity Register",
          "Work with Machines and Materials",
          "Maker Skills",
          "Animation and Games",
          "School Museum",
          "Cooking without Fire",
        ],
      },
      hindi: {
        topics: [
          "Maatbhumi",
          "Pushp ki abhilasha",
          "Gol",
          "Ek daud aisi bhi",
          "Pehli bund",
          "Haar ki jeet",
          "Raheem ke dohe",
          "Meri maa",
          "Jalate chalo",
          "Sattriya aur Bihu nritya",
          "Maiya main nahi makhan khayo",
          "Pariksha",
          "Chetak ki veerta",
          "Hind Mahasagar mein chhota-sa Hindustan",
          "Ped ki baat",
          "Aao bachcho tumhe dikhaye jhanki Hindustan ki",
        ],
      },
      sanskrit: {
        topics: [
          "Vayam varnamalam pathamah",
          "Sanyukt-vyanjanani",
          "Eshah kah? Esha ka? Etat kim?",
          "Aham cha tvam cha",
          "Sankhyaganana",
          "Aham pratah utishthami",
          "Shoorah vayam dheerah vayam",
          "Sah eva mahan chitrakarah",
          "Atithidevo bhava",
          "Buddhih sarvarthasadhika",
          "Yah janati sah panditah",
          "Tvam aapanam gachchha",
          "Prithivyam trini ratnani",
          "Alasyam hi manushyanam sharirasthah mahan ripuh",
          "Madhavasya priyam angam",
          "Vrikshah satpurushah iva",
        ],
      },
    },
    "Class 7": {
      Arts: {
        topics: [
          "Understanding Emotions",
          "Say More without Speech—Mime",
          "Let’s Design—Stage Technicals",
          "Story of India’s Storytelling Tradition",
          "Making Music",
          "Music, Emotions and Creativity",
          "Ragas and Talas/Taal",
          "The Music of the People",
          "Performance",
          "Dance Vocabulary and Techniques",
          "Dance, You and Creativity",
          "Personalities",
          "Natya",
          "Objects in Icons and Symbols",
          "Nature’s Palette",
          "How You Feel",
          "Textiles and Traditions",
          "The Art of Calligraphy",
          "Integration of All Art Forms—Sculptures Come Alive",
        ],
      },
      English: {
        topics: [
          "The Day the River Spoke",
          "Try Again",
          "Three Days to See",
          "Animals, Birds, and Dr. Dolittle",
          "A Funny Man",
          "Say the Right Thing",
          "My Brother’s Great Invention",
          "Paper Boats",
          "North, South, East, West",
          "The Tunnel",
          "Travel",
          "Conquering the Summit",
          "A Homage to Our Brave Soldiers",
          "My Dear Soldiers",
          "Rani Abbakka",
        ],
      },
      Maths: {
        topics: [
          "Large Numbers Around Us",
          "Arithmetic Expressions",
          "A Peek Beyond the Point",
          "Expressions using Letter-Numbers",
          "Parallel and Intersecting Lines",
          "Number Play",
          "A Tale of Three Intersecting Lines",
          "Working with Fractions",
          "Geometric Twins",
          "Operations with Integers",
          "Finding Common Ground",
          "Another Peek Beyond the Point",
          "Connecting the Dots",
          "Constructions and Tilings",
          "Finding the Unknown",
        ],
      },
      "Physical Education": {
        topics: [
          "The Ball Progression Game",
          "Ghorpadiche Shepoot",
          "Nalugu Rallu Ata",
          "Gidhada Gudkavan",
          "Stand Up, Speak Out",
          "Harassment Prevention Skit",
          "Set It Up, Knock It Down",
          "Dhaan Ki Bori",
          "Caterpillar Race",
          "Count and Connect Game",
          "Skipping Race",
          "Atya-patya",
          "Food for Health",
          "Dapo Nyarka Sunam",
          "Madhu and Manu",
          "Skipping Song",
          "Forehand Grip and Air Toss",
          "Backhand Grip and Air Toss",
          "Footwork Skills",
          "Backhand Low Serve",
          "Backhand Lift",
          "Forehand Lift",
          "Forehand High Serve",
          "Forehand Low Serve",
          "Forehand Drive",
          "Backhand Drive",
          "Forehand Clear",
          "Forehand Drop",
          "Badminton Match",
          "Kicking the Ball with the Inside of the Foot",
          "Receiving the Ball by Inside of the Foot",
          "Passing the Rolling Ball",
          "Step Trapping",
          "Dribble",
          "Feinting",
          "Kicking the Ball for Accuracy",
          "Passing the Ball in the Air",
          "Pass and Move Relay Drill",
          "Interception",
          "Front Block Tackling",
          "Goal Keeping",
          "5-a-side Match",
          "Raiding Foot Work",
          "Hand Touch",
          "Toe Touch",
          "Kick",
          "Ankle-hold",
          "Thigh-hold",
          "Knee-hold",
          "Wrist-hold",
          "Waist-hold",
          "Chain-hold",
          "Yoga for Daily Life",
          "Yoga Sadhana",
          "Āsana",
          "Prānāyāma",
        ],
      },
      Science: {
        topics: [
          "The Ever-Evolving World of Science",
          "Exploring Substances: Acidic, Basic, and Neutral",
          "Electricity: Circuits and their Components",
          "The World of Metals and Non-metals",
          "Changes Around Us: Physical and Chemical",
          "Adolescence: A Stage of Growth and Change",
          "Heat Transfer in Nature",
          "Measurement of Time and Motion",
          "Life Processes in Animals",
          "Life Processes in Plants",
          "Light: Shadows and Reflections",
          "Earth, Moon, and the Sun",
        ],
      },
      "Social Science": {
        topics: [
          "Geographical Diversity of India",
          "Understanding the Weather",
          "Climates of India",
          "New Beginnings: Cities and States",
          "The Rise of Empires",
          "The Age of Reorganisation",
          "The Gupta Era: An Age of Tireless Creativity",
          "How the Land Becomes Sacred",
          "From the Rulers to the Ruled: Types of Governments",
          "The Constitution of India — An Introduction",
          "From Barter to Money",
          "Understanding Markets",
          "Political Map of India",
          "Physical Map of India",
          "The Story of Indian Farming",
          "India and Her Neighbours",
          "Empires and Kingdoms: 6th to 10th Centuries",
          "Turning Tides: 11th and 12th Centuries",
          "India, a Home to Many",
          "The State, the Government, and You",
          "Infrastructure: Engine of India’s Development",
          "Banks and the Magic of Finance",
        ],
      },
      "Vocational Education": {
        topics: [
          "Plant Nursery",
          "School Habitat Garden",
          "Work with Machines and Materials",
          "Tie and Dye",
          "AI Assistant",
          "Storytime with Puppets",
          "Family Health Handbook",
        ],
      },
      hindi: {
        topics: [
          "Maan, kah ek kahani",
          "Teen buddhimaan",
          "Phool aur kaanta",
          "Paani re paani",
          "Nahi hona beemar",
          "Giridhar Kavirai ka kundaliya",
          "Varsha-bahar",
          "Birju Maharaj se sakshatkar",
          "Natyaganan sandhi",
          "Dheediya",
          "Meera ke pad",
        ],
      },
      sanskrit: {
        topics: [
          "Vande Bharat Matram",
          "Nityam pibamah subhashita rasam",
          "Mitraya namah",
          "Na labhyate chet amlam draksha phalam",
          "Seva hi paramo dharmah",
          "Kridama vayam shlokantyaksheem",
          "Ishavasya midam sarvam",
          "Hitam manohari cha durlabham vachah",
          "Annad bhavanti bhutani",
          "Dashamah kah?",
          "Dweepeshu ramyah dweepo andamanah",
          "Veerangana Pannadhaya",
        ],
      },
    },

    "Class 8": {
      Arts: {
        topics: [
          "Bringing Words Alive—Play Reading",
          "One Stage, Many Scripts",
          "From Page to Stage",
          "Applause and Advice",
          "Discovering the Elements of Music",
          "Musical Instruments",
          "Indian Classical Music",
          "Inspiration and Imagination",
          "My World of Music",
          "Inner Dynamics of Dance",
          "Pan Indian Dance Forms",
          "Dance for Well-being",
          "Innovation, Inclusivity and Inspiring Change",
          "A Presentation of Dance and Choreography",
          "Elements and Principles of Visual Art and Design",
          "Still Life in Colour",
          "People in Places",
          "Arts of the People, With the People, For the People",
          "Campaign for Art Awareness",
        ],
      },
      English: {
        topics: [
          "The Wit that Won Hearts",
          "A Concrete Example",
          "Wisdom Paves the Way",
          "A Tale of Valour: Major Somnath Sharma and the Battle of Badgam",
          "Somebody’s Mother",
          "Verghese Kurien—I Too Had A Dream",
          "The Case of the Fifth Word",
          "The Magic Brush of Dreams",
          "Spectacular Wonders",
          "The Cherry Tree",
          "Harvest Hymn",
          "Waiting for the Rain",
          "Feathered Friend",
          "Magnifying Glass",
          "Bibha Chowdhuri: The Beam of Light that Lit the Path for Women in Indian Science",
        ],
      },
      Maths: {
        topics: [
          "A Square and A Cube",
          "Power Play",
          "A Story of Numbers",
          "Quadrilaterals",
          "Number Play",
          "We Distribute, Yet Things Multiply",
          "Proportional Reasoning-1",
          "Fractions in Disguise",
          "The Baudhayana-Pythagoras Theorem",
          "Proportional Reasoning-2",
          "Exploring Some Geometric Themes",
          "Tales by Dots and Lines",
          "Algebra Play",
          "Area",
        ],
      },
      "Physical Education": {
        topics: [
          "Horse Vault Race",
          "Progressive Mass Drill",
          "Baraf Pānī",
          "Chār Tālī",
          "Conduction Relay",
          "Motion-in-Action Relay",
          "Breathing in Action",
          "Flex and React Challenge",
          "Move Like a Machine",
          "Adapt and Achieve",
          "Crawl to the Front",
          "Rock-Paper-Championship Run",
          "Modified Triathlon Activity",
          "Pass, Sit, and Score",
          "Crab Crawl Ball Relay",
          "Hitting Running Target Game",
          "Kick Volleyball",
          "Ropeless Tug of War",
          "Swāsthya Dauḍ",
          "Crouch or Sitting Start",
          "Chase and Tag",
          "Reaction Game",
          "Long Jump",
          "Standing Broad Jump",
          "Hopping",
          "Making an Arch",
          "Landing",
          "High Jump",
          "Heading Suspended Ball",
          "Trikoṇa Kainchī Kūda",
          "Putting Ball",
          "Grip",
          "Footwork",
          "Forehand Push",
          "Backhand Push",
          "Basic Service",
          "Topspin Service",
          "Backspin Service",
          "Forehand Drive",
          "Backhand Drive",
          "Forehand Topspin",
          "Backhand Topspin",
          "Smash",
          "Table Tennis Game",
          "Underhand Pass",
          "Overhead Pass",
          "Underhand Serve",
          "Overhead Serve",
          "Setting",
          "Spike",
          "Block",
          "Dig",
          "Ball Rotation Activity",
          "Ace Accuracy Contest",
          "Ball Throw Activity",
          "11-Point Match",
          "Yoga for Daily Life",
          "Yoga Sādhanā",
          "Āsanā",
          "Prānāyāma",
        ],
      },
      Science: {
        topics: [
          "Exploring the Investigative World of Science",
          "The Invisible Living World: Beyond Our Naked Eye",
          "Health: The Ultimate Treasure",
          "Electricity: Magnetic and Heating Effects",
          "Exploring Forces",
          "Pressure, Winds, Storms, and Cyclones",
          "Particulate Nature of Matter",
          "Nature of Matter: Elements, Compounds, and Mixtures",
          "The Amazing World of Solutes, Solvents, and Solutions",
          "Light: Mirrors and Lenses",
          "Keeping Time with the Skies",
          "How Nature Works in Harmony",
          "Our Home: Earth, a Unique Life Sustaining Planet",
        ],
      },
      "Social Science": {
        topics: [
          "Natural Resources and Their Use",
          "A Note on History’s Darker Periods",
          "Reshaping India’s Political Map",
          "The Rise of the Marathas",
          "The Colonial Era in India",
          "Universal Franchise and India’s Electoral System",
          "The Parliamentary System: Legislature and Executive",
          "Factors of Production",
        ],
      },
      "Vocational Education": {
        topics: [
          "Hydroponics: Growing Plants without Soil",
          "Feeding and Caring for Farm Animals",
          "Working with Wood and Bamboo",
          "Home Automation",
          "Water Audit for Water Management",
          "Creating Advertisements",
        ],
      },
      hindi: {
        topics: [
          "Swadesh",
          "Do gauraiya",
          "Mitralaabh",
          "Ek aashirvaad",
          "Haridwar",
          "Kabir ke dohe",
          "Kadam milakar chalna hoga",
          "Ek tokri bhar mitti",
          "Mat baandho",
          "Naye mehmaan",
          "Aadmi ka anupaat",
          "Tarun ke swapn",
        ],
      },
      sanskrit: {
        topics: [
          "Sangachchhadhvam samvadadhvam",
          "Alpanamapi vastunam samhatih karyasadhika",
          "Subhashitarasam peetva jeevanam saphalam kuru",
          "Pranamyo deshbhakto'yam Gopabandhurmahamanah",
          "Gita sugita kartavya",
          "Digi Bharatam yugaparivartanam",
          "Manjulamanjusha sundarasurabhasha",
          "Pashyata konam aishanyam Bharatasya manoharam",
          "Ko'ruk? Ko'ruk? Ko'ruk?",
          "Sannimitte varam tyagah (part 1)",
          "Sannimitte varam tyagah (part 2)",
          "Samyag varna prayogena brahmaloke mahiyate",
          "Varnoccharan shiksha",
        ],
      },
    },
  },
};
