insert into topic_suggestions (board, class, subject, topic) values
('CBSE', '1', 'Maths', 'Numbers 1-100'),
('CBSE', '1', 'Maths', 'Addition'),
('CBSE', '1', 'Maths', 'Subtraction'),
('CBSE', '1', 'Maths', 'Shapes'),
('CBSE', '1', 'Maths', 'Patterns'),
('CBSE', '1', 'EVS', 'Myself'),
('CBSE', '1', 'EVS', 'Family'),
('CBSE', '1', 'EVS', 'Plants'),
('CBSE', '1', 'EVS', 'Animals'),
('CBSE', '1', 'EVS', 'Food'),
('CBSE', '1', 'EVS', 'Water'),
('CBSE', '1', 'English Grammar', 'Alphabet'),
('CBSE', '1', 'English Grammar', 'Basic Words'),
('CBSE', '1', 'English Grammar', 'Simple Sentences'),
('CBSE', '1', 'Hindi Vyakran', 'Varnmala'),
('CBSE', '1', 'Hindi Vyakran', 'Basic Words'),
('CBSE', '1', 'Hindi Vyakran', 'Simple Sentences'),
('CBSE', '1', 'Computer', 'Computer Basics'),
('CBSE', '1', 'Computer', 'Uses of Computer'),
('CBSE', '2', 'Maths', 'Numbers up to 1000'),
('CBSE', '2', 'Maths', 'Addition'),
('CBSE', '2', 'Maths', 'Subtraction'),
('CBSE', '2', 'Maths', 'Multiplication Basics'),
('CBSE', '2', 'EVS', 'Plants'),
('CBSE', '2', 'EVS', 'Animals'),
('CBSE', '2', 'EVS', 'Human Body'),
('CBSE', '2', 'EVS', 'Transport'),
('CBSE', '2', 'EVS', 'Safety'),
('CBSE', '2', 'English Grammar', 'Nouns'),
('CBSE', '2', 'English Grammar', 'Pronouns'),
('CBSE', '2', 'English Grammar', 'Verbs'),
('CBSE', '2', 'Hindi Vyakran', 'Sangya'),
('CBSE', '2', 'Hindi Vyakran', 'Sarvanaam'),
('CBSE', '2', 'Hindi Vyakran', 'Kriya'),
('CBSE', '2', 'Computer', 'Parts of Computer'),
('CBSE', '2', 'Computer', 'Input Devices'),
('CBSE', '3', 'Maths', 'Place Value'),
('CBSE', '3', 'Maths', 'Multiplication'),
('CBSE', '3', 'Maths', 'Division'),
('CBSE', '3', 'Maths', 'Fractions'),
('CBSE', '3', 'EVS', 'Living & Non-living'),
('CBSE', '3', 'EVS', 'Food'),
('CBSE', '3', 'EVS', 'Water'),
('CBSE', '3', 'EVS', 'Shelter'),
('CBSE', '3', 'English Grammar', 'Parts of Speech'),
('CBSE', '3', 'English Grammar', 'Basic Tenses'),
('CBSE', '3', 'Hindi Vyakran', 'Ling'),
('CBSE', '3', 'Hindi Vyakran', 'Vachan'),
('CBSE', '3', 'Hindi Vyakran', 'Kriya'),
('CBSE', '3', 'Computer', 'Keyboard'),
('CBSE', '3', 'Computer', 'Basic Software'),
('CBSE', '4', 'Maths', 'Large Numbers'),
('CBSE', '4', 'Maths', 'Fractions'),
('CBSE', '4', 'Maths', 'Decimals'),
('CBSE', '4', 'Maths', 'Geometry'),
('CBSE', '4', 'EVS', 'Plants'),
('CBSE', '4', 'EVS', 'Animals'),
('CBSE', '4', 'EVS', 'Natural Resources'),
('CBSE', '4', 'EVS', 'States of India'),
('CBSE', '4', 'English Grammar', 'Tenses'),
('CBSE', '4', 'English Grammar', 'Adjectives'),
('CBSE', '4', 'English Grammar', 'Prepositions'),
('CBSE', '4', 'Hindi Vyakran', 'Sangya'),
('CBSE', '4', 'Hindi Vyakran', 'Sarvanaam'),
('CBSE', '4', 'Hindi Vyakran', 'Kaal'),
('CBSE', '4', 'Computer', 'MS Paint'),
('CBSE', '4', 'Computer', 'Basic Applications'),
('CBSE', '5', 'Maths', 'Decimals'),
('CBSE', '5', 'Maths', 'Fractions'),
('CBSE', '5', 'Maths', 'Measurement'),
('CBSE', '5', 'Maths', 'Data Handling'),
('CBSE', '5', 'EVS', 'Human Body'),
('CBSE', '5', 'EVS', 'Energy'),
('CBSE', '5', 'EVS', 'Environment'),
('CBSE', '5', 'EVS', 'Indian Geography'),
('CBSE', '5', 'English Grammar', 'Tenses'),
('CBSE', '5', 'English Grammar', 'Articles'),
('CBSE', '5', 'English Grammar', 'Conjunctions'),
('CBSE', '5', 'Hindi Vyakran', 'Kaal'),
('CBSE', '5', 'Hindi Vyakran', 'Vakya'),
('CBSE', '5', 'Hindi Vyakran', 'Muhavare'),
('CBSE', '5', 'Computer', 'MS Word'),
('CBSE', '5', 'Computer', 'Internet Basics'),
('CBSE', '6', 'Maths', 'Integers'),
('CBSE', '6', 'Maths', 'Fractions'),
('CBSE', '6', 'Maths', 'Ratio'),
('CBSE', '6', 'Maths', 'Algebra'),
('CBSE', '6', 'Maths', 'Mensuration'),
('CBSE', '6', 'Science', 'Food'),
('CBSE', '6', 'Science', 'Materials'),
('CBSE', '6', 'Science', 'Motion'),
('CBSE', '6', 'Science', 'Light'),
('CBSE', '6', 'Science', 'Electricity'),
('CBSE', '6', 'SST', 'Ancient History'),
('CBSE', '6', 'SST', 'Geography'),
('CBSE', '6', 'SST', 'Civics'),
('CBSE', '6', 'English Grammar', 'Grammar'),
('CBSE', '6', 'English Grammar', 'Writing Skills'),
('CBSE', '6', 'Hindi Vyakran', 'Sandhi'),
('CBSE', '6', 'Hindi Vyakran', 'Samas'),
('CBSE', '6', 'Hindi Vyakran', 'Kaal'),
('CBSE', '6', 'Computer', 'MS Office'),
('CBSE', '6', 'Computer', 'Internet'),
('CBSE', '7', 'Maths', 'Algebra'),
('CBSE', '7', 'Maths', 'Ratio'),
('CBSE', '7', 'Maths', 'Geometry'),
('CBSE', '7', 'Maths', 'Mensuration'),
('CBSE', '7', 'Science', 'Heat'),
('CBSE', '7', 'Science', 'Acids & Bases'),
('CBSE', '7', 'Science', 'Motion'),
('CBSE', '7', 'Science', 'Electricity'),
('CBSE', '7', 'SST', 'Medieval History'),
('CBSE', '7', 'SST', 'Environment'),
('CBSE', '7', 'SST', 'Democracy'),
('CBSE', '7', 'English Grammar', 'Tenses'),
('CBSE', '7', 'English Grammar', 'Voice'),
('CBSE', '7', 'English Grammar', 'Writing Skills'),
('CBSE', '7', 'Hindi Vyakran', 'Samas'),
('CBSE', '7', 'Hindi Vyakran', 'Kaal'),
('CBSE', '7', 'Hindi Vyakran', 'Vakya Bhed'),
('CBSE', '7', 'Computer', 'Spreadsheets'),
('CBSE', '7', 'Computer', 'Internet Tools'),
('CBSE', '8', 'Maths', 'Linear Equations'),
('CBSE', '8', 'Maths', 'Squares'),
('CBSE', '8', 'Maths', 'Mensuration'),
('CBSE', '8', 'Maths', 'Graphs'),
('CBSE', '8', 'Science', 'Force'),
('CBSE', '8', 'Science', 'Light'),
('CBSE', '8', 'Science', 'Sound'),
('CBSE', '8', 'Science', 'Microorganisms'),
('CBSE', '8', 'Science', 'Friction'),
('CBSE', '8', 'SST', 'Modern History'),
('CBSE', '8', 'SST', 'Resources'),
('CBSE', '8', 'SST', 'Constitution'),
('CBSE', '8', 'English Grammar', 'Grammar'),
('CBSE', '8', 'English Grammar', 'Writing'),
('CBSE', '8', 'English Grammar', 'Literature'),
('CBSE', '8', 'Hindi Vyakran', 'Sandhi'),
('CBSE', '8', 'Hindi Vyakran', 'Samas'),
('CBSE', '8', 'Hindi Vyakran', 'Muhavare'),
('CBSE', '8', 'Computer', 'Basics of Programming'),
('CBSE', '8', 'Computer', 'Internet'),
('ICSE', '1', 'Maths', 'Numbers'),
('ICSE', '1', 'Maths', 'Addition'),
('ICSE', '1', 'Maths', 'Subtraction'),
('ICSE', '1', 'Maths', 'Shapes'),
('ICSE', '1', 'EVS', 'Myself'),
('ICSE', '1', 'EVS', 'Plants'),
('ICSE', '1', 'EVS', 'Animals'),
('ICSE', '1', 'EVS', 'Food'),
('ICSE', '1', 'English Grammar', 'Alphabet'),
('ICSE', '1', 'English Grammar', 'Words'),
('ICSE', '1', 'English Grammar', 'Sentences'),
('ICSE', '1', 'Hindi Vyakran', 'Varnmala'),
('ICSE', '1', 'Hindi Vyakran', 'Words'),
('ICSE', '1', 'Computer', 'Computer Basics'),
('ICSE', '2', 'Maths', 'Numbers'),
('ICSE', '2', 'Maths', 'Addition'),
('ICSE', '2', 'Maths', 'Subtraction'),
('ICSE', '2', 'Maths', 'Multiplication'),
('ICSE', '2', 'EVS', 'Plants'),
('ICSE', '2', 'EVS', 'Animals'),
('ICSE', '2', 'EVS', 'Transport'),
('ICSE', '2', 'EVS', 'Safety'),
('ICSE', '2', 'English Grammar', 'Nouns'),
('ICSE', '2', 'English Grammar', 'Verbs'),
('ICSE', '2', 'English Grammar', 'Pronouns'),
('ICSE', '2', 'Hindi Vyakran', 'Sangya'),
('ICSE', '2', 'Hindi Vyakran', 'Kriya'),
('ICSE', '2', 'Hindi Vyakran', 'Sarvanaam'),
('ICSE', '2', 'Computer', 'Parts of Computer'),
('ICSE', '3', 'Maths', 'Place Value'),
('ICSE', '3', 'Maths', 'Fractions'),
('ICSE', '3', 'Maths', 'Measurement'),
('ICSE', '3', 'EVS', 'Living & Non-living'),
('ICSE', '3', 'EVS', 'Food'),
('ICSE', '3', 'EVS', 'Water'),
('ICSE', '3', 'English Grammar', 'Grammar Basics'),
('ICSE', '3', 'English Grammar', 'Tenses'),
('ICSE', '3', 'Hindi Vyakran', 'Ling'),
('ICSE', '3', 'Hindi Vyakran', 'Vachan'),
('ICSE', '3', 'Computer', 'Hardware'),
('ICSE', '3', 'Computer', 'Software'),
('ICSE', '4', 'Maths', 'Fractions'),
('ICSE', '4', 'Maths', 'Decimals'),
('ICSE', '4', 'Maths', 'Geometry'),
('ICSE', '4', 'Science', 'Plants'),
('ICSE', '4', 'Science', 'Animals'),
('ICSE', '4', 'Science', 'Matter'),
('ICSE', '4', 'SST', 'Geography'),
('ICSE', '4', 'SST', 'History'),
('ICSE', '4', 'English Grammar', 'Tenses'),
('ICSE', '4', 'English Grammar', 'Adjectives'),
('ICSE', '4', 'Hindi Vyakran', 'Kaal'),
('ICSE', '4', 'Hindi Vyakran', 'Vakya'),
('ICSE', '4', 'Computer', 'MS Paint'),
('ICSE', '5', 'Maths', 'Fractions'),
('ICSE', '5', 'Maths', 'Geometry'),
('ICSE', '5', 'Maths', 'Measurement'),
('ICSE', '5', 'Science', 'Human Body'),
('ICSE', '5', 'Science', 'Energy'),
('ICSE', '5', 'Science', 'Plants'),
('ICSE', '5', 'SST', 'History'),
('ICSE', '5', 'SST', 'Geography'),
('ICSE', '5', 'SST', 'Civics'),
('ICSE', '5', 'English Grammar', 'Tenses'),
('ICSE', '5', 'English Grammar', 'Articles'),
('ICSE', '5', 'Hindi Vyakran', 'Kaal'),
('ICSE', '5', 'Hindi Vyakran', 'Muhavare'),
('ICSE', '5', 'Computer', 'MS Word'),
('ICSE', '6', 'Maths', 'Integers'),
('ICSE', '6', 'Maths', 'Algebra'),
('ICSE', '6', 'Maths', 'Ratio'),
('ICSE', '6', 'Science', 'Physics'),
('ICSE', '6', 'Science', 'Chemistry'),
('ICSE', '6', 'Science', 'Biology'),
('ICSE', '6', 'SST', 'History'),
('ICSE', '6', 'SST', 'Civics'),
('ICSE', '6', 'SST', 'Geography'),
('ICSE', '6', 'English Grammar', 'Grammar'),
('ICSE', '6', 'English Grammar', 'Writing'),
('ICSE', '6', 'Hindi Vyakran', 'Sandhi'),
('ICSE', '6', 'Hindi Vyakran', 'Samas'),
('ICSE', '6', 'Computer', 'MS Office'),
('ICSE', '7', 'Maths', 'Algebra'),
('ICSE', '7', 'Maths', 'Mensuration'),
('ICSE', '7', 'Maths', 'Geometry'),
('ICSE', '7', 'Science', 'Heat'),
('ICSE', '7', 'Science', 'Acids'),
('ICSE', '7', 'Science', 'Motion'),
('ICSE', '7', 'SST', 'Medieval History'),
('ICSE', '7', 'SST', 'Civics'),
('ICSE', '7', 'English Grammar', 'Tenses'),
('ICSE', '7', 'English Grammar', 'Voice'),
('ICSE', '7', 'Hindi Vyakran', 'Samas'),
('ICSE', '7', 'Hindi Vyakran', 'Vakya'),
('ICSE', '7', 'Computer', 'Spreadsheets'),
('ICSE', '8', 'Maths', 'Linear Equations'),
('ICSE', '8', 'Maths', 'Graphs'),
('ICSE', '8', 'Maths', 'Mensuration'),
('ICSE', '8', 'Science', 'Physics'),
('ICSE', '8', 'Science', 'Chemistry'),
('ICSE', '8', 'Science', 'Biology'),
('ICSE', '8', 'SST', 'Modern History'),
('ICSE', '8', 'SST', 'Geography'),
('ICSE', '8', 'English Grammar', 'Grammar'),
('ICSE', '8', 'English Grammar', 'Writing'),
('ICSE', '8', 'Hindi Vyakran', 'Sandhi'),
('ICSE', '8', 'Hindi Vyakran', 'Muhavare'),
('ICSE', '8', 'Computer', 'Programming Basics'),
('State Board', '1', 'Maths', 'Numbers'),
('State Board', '1', 'Maths', 'Addition'),
('State Board', '1', 'Maths', 'Shapes'),
('State Board', '1', 'EVS', 'Family'),
('State Board', '1', 'EVS', 'Plants'),
('State Board', '1', 'EVS', 'Animals'),
('State Board', '1', 'English Grammar', 'Alphabet'),
('State Board', '1', 'English Grammar', 'Words'),
('State Board', '1', 'Hindi Vyakran', 'Varnmala'),
('State Board', '2', 'Maths', 'Numbers'),
('State Board', '2', 'Maths', 'Addition'),
('State Board', '2', 'Maths', 'Subtraction'),
('State Board', '2', 'EVS', 'Plants'),
('State Board', '2', 'EVS', 'Animals'),
('State Board', '2', 'EVS', 'Transport'),
('State Board', '2', 'English Grammar', 'Words'),
('State Board', '2', 'English Grammar', 'Sentences'),
('State Board', '2', 'Hindi Vyakran', 'Words'),
('State Board', '2', 'Hindi Vyakran', 'Simple Sentences'),
('State Board', '3', 'Maths', 'Multiplication'),
('State Board', '3', 'Maths', 'Division'),
('State Board', '3', 'Maths', 'Fractions'),
('State Board', '3', 'EVS', 'Food'),
('State Board', '3', 'EVS', 'Water'),
('State Board', '3', 'EVS', 'Shelter'),
('State Board', '3', 'English Grammar', 'Grammar Basics'),
('State Board', '3', 'Hindi Vyakran', 'Ling'),
('State Board', '3', 'Hindi Vyakran', 'Vachan'),
('State Board', '3', 'Computer', 'Basic Computer'),
('State Board', '4', 'Maths', 'Fractions'),
('State Board', '4', 'Maths', 'Decimals'),
('State Board', '4', 'Maths', 'Geometry'),
('State Board', '4', 'Science', 'Plants'),
('State Board', '4', 'Science', 'Animals'),
('State Board', '4', 'Science', 'Matter'),
('State Board', '4', 'SST', 'Geography'),
('State Board', '4', 'SST', 'History'),
('State Board', '4', 'English Grammar', 'Tenses'),
('State Board', '4', 'Hindi Vyakran', 'Kaal'),
('State Board', '5', 'Maths', 'Fractions'),
('State Board', '5', 'Maths', 'Measurement'),
('State Board', '5', 'Maths', 'Data Handling'),
('State Board', '5', 'Science', 'Human Body'),
('State Board', '5', 'Science', 'Energy'),
('State Board', '5', 'SST', 'History'),
('State Board', '5', 'SST', 'Geography'),
('State Board', '5', 'English Grammar', 'Tenses'),
('State Board', '5', 'English Grammar', 'Articles'),
('State Board', '5', 'Hindi Vyakran', 'Vakya'),
('State Board', '5', 'Hindi Vyakran', 'Muhavare'),
('State Board', '6', 'Maths', 'Integers'),
('State Board', '6', 'Maths', 'Algebra'),
('State Board', '6', 'Maths', 'Ratio'),
('State Board', '6', 'Science', 'Food'),
('State Board', '6', 'Science', 'Light'),
('State Board', '6', 'Science', 'Materials'),
('State Board', '6', 'SST', 'History'),
('State Board', '6', 'SST', 'Civics'),
('State Board', '6', 'SST', 'Geography'),
('State Board', '6', 'English Grammar', 'Grammar'),
('State Board', '6', 'English Grammar', 'Writing'),
('State Board', '6', 'Hindi Vyakran', 'Sandhi'),
('State Board', '7', 'Maths', 'Algebra'),
('State Board', '7', 'Maths', 'Geometry'),
('State Board', '7', 'Maths', 'Mensuration'),
('State Board', '7', 'Science', 'Heat'),
('State Board', '7', 'Science', 'Acids'),
('State Board', '7', 'Science', 'Motion'),
('State Board', '7', 'SST', 'History'),
('State Board', '7', 'SST', 'Environment'),
('State Board', '7', 'English Grammar', 'Tenses'),
('State Board', '7', 'English Grammar', 'Voice'),
('State Board', '7', 'Hindi Vyakran', 'Samas'),
('State Board', '8', 'Maths', 'Algebra'),
('State Board', '8', 'Maths', 'Mensuration'),
('State Board', '8', 'Maths', 'Linear Equations'),
('State Board', '8', 'Science', 'Physics'),
('State Board', '8', 'Science', 'Chemistry'),
('State Board', '8', 'Science', 'Biology'),
('State Board', '8', 'SST', 'Modern History'),
('State Board', '8', 'SST', 'Civics'),
('State Board', '8', 'English Grammar', 'Grammar'),
('State Board', '8', 'English Grammar', 'Writing'),
('State Board', '8', 'Hindi Vyakran', 'Sandhi'),
('State Board', '8', 'Hindi Vyakran', 'Muhavare'),
('NCERT', '1', 'Maths', 'Finding the Furry Cat'),
('NCERT', '1', 'Maths', 'What is Long? What is Round?'),
('NCERT', '1', 'Maths', 'Mango Treat'),
('NCERT', '1', 'Maths', 'Making 10'),
('NCERT', '1', 'Maths', 'How Many? (Addition and Subtraction of Single Digit Numbers)'),
('NCERT', '1', 'Maths', 'Vegetable Farm (Addition and Subtraction up to 20)'),
('NCERT', '1', 'Maths', 'Lina’s Family (Measurement)'),
('NCERT', '1', 'Maths', 'Fun with Numbers (Numbers 21 to 99)'),
('NCERT', '1', 'Maths', 'Utsav (Patterns)'),
('NCERT', '1', 'Maths', 'How do I Spend my Day? (Time)'),
('NCERT', '1', 'Maths', 'How Many Times? (Multiplication)'),
('NCERT', '1', 'Maths', 'How Much Can We Spend? (Money)'),
('NCERT', '1', 'Maths', 'So Many Toys (Data Handling)'),
('NCERT', '1', 'English Grammar', 'Two Little Hands'),
('NCERT', '1', 'English Grammar', 'Greetings'),
('NCERT', '1', 'English Grammar', 'Picture Time'),
('NCERT', '1', 'English Grammar', 'The Cap-seller and the Monkeys'),
('NCERT', '1', 'English Grammar', 'A Farm'),
('NCERT', '1', 'English Grammar', 'Fun with Pictures'),
('NCERT', '1', 'English Grammar', 'The Food we Eat'),
('NCERT', '1', 'English Grammar', 'The Four Seasons'),
('NCERT', '1', 'English Grammar', 'Anandi’s Rainbow'),
('NCERT', '1', 'Hindi Vyakran', 'Meena ka parivaar'),
('NCERT', '1', 'Hindi Vyakran', 'Chanda mama door ke'),
('NCERT', '1', 'Hindi Vyakran', 'Dada-dadi'),
('NCERT', '1', 'Hindi Vyakran', 'Reena ka din'),
('NCERT', '1', 'Hindi Vyakran', 'Rani bhi'),
('NCERT', '1', 'Hindi Vyakran', 'Murgabola kukdu-koo'),
('NCERT', '1', 'Hindi Vyakran', 'Mithai'),
('NCERT', '1', 'Hindi Vyakran', 'Teen saathi'),
('NCERT', '1', 'Hindi Vyakran', 'Wah, mere ghode'),
('NCERT', '1', 'Hindi Vyakran', 'Khatre mein saanp'),
('NCERT', '1', 'Hindi Vyakran', 'Kabri jhabri bakri'),
('NCERT', '1', 'Hindi Vyakran', 'Aloo ki sada'),
('NCERT', '1', 'Hindi Vyakran', 'Jhoolam-jhooli'),
('NCERT', '1', 'Hindi Vyakran', 'Bhutte'),
('NCERT', '1', 'Hindi Vyakran', 'Phooli roti'),
('NCERT', '1', 'Hindi Vyakran', 'Mela'),
('NCERT', '1', 'Hindi Vyakran', 'Barkha aur Megha'),
('NCERT', '1', 'Hindi Vyakran', 'Holi'),
('NCERT', '1', 'Hindi Vyakran', 'Janmdin par ped lagao'),
('NCERT', '1', 'Hindi Vyakran', 'Hawa'),
('NCERT', '1', 'Hindi Vyakran', 'Kitni pyari hai ye duniya'),
('NCERT', '1', 'Hindi Vyakran', 'Chaand ka bachcha'),
('NCERT', '2', 'Maths', 'A Day at the Beach (Counting in Groups)'),
('NCERT', '2', 'Maths', 'Shapes Around Us (3D Shapes)'),
('NCERT', '2', 'Maths', 'Fun with Numbers (Numbers 1 to 100)'),
('NCERT', '2', 'Maths', 'Shadow Story (Togalu) (2D Shapes)'),
('NCERT', '2', 'Maths', 'Playing with Lines (Orientations of a line)'),
('NCERT', '2', 'Maths', 'Decoration for Festival (Addition and Subtraction)'),
('NCERT', '2', 'Maths', 'Rani’s Gift (Measurement)'),
('NCERT', '2', 'Maths', 'Grouping and Sharing (Multiplication and Division)'),
('NCERT', '2', 'Maths', 'Which Season is it? (Measurement of Time)'),
('NCERT', '2', 'Maths', 'Fun at the Fair (Money)'),
('NCERT', '2', 'Maths', 'Data Handling'),
('NCERT', '2', 'English Grammar', 'My Bicycle'),
('NCERT', '2', 'English Grammar', 'Picture Reading'),
('NCERT', '2', 'English Grammar', 'It is Fun'),
('NCERT', '2', 'English Grammar', 'Seeing without Seeing '),
('NCERT', '2', 'English Grammar', 'Come Back Soon'),
('NCERT', '2', 'English Grammar', 'Between Home and School'),
('NCERT', '2', 'English Grammar', 'This is My Town'),
('NCERT', '2', 'English Grammar', 'A Show of Clouds'),
('NCERT', '2', 'English Grammar', 'My Name'),
('NCERT', '2', 'English Grammar', 'The Crow'),
('NCERT', '2', 'English Grammar', 'The Smart Monkey'),
('NCERT', '2', 'English Grammar', 'Little Drops of Water'),
('NCERT', '2', 'English Grammar', 'We are all Indians'),
('NCERT', '2', 'Hindi Vyakran', 'Neema ki Dadi'),
('NCERT', '2', 'Hindi Vyakran', 'Ghar'),
('NCERT', '2', 'Hindi Vyakran', 'Mala ki Chandi ki Payal'),
('NCERT', '2', 'Hindi Vyakran', 'Maa'),
('NCERT', '2', 'Hindi Vyakran', 'Thath aur Main'),
('NCERT', '2', 'Hindi Vyakran', 'Cheenta'),
('NCERT', '2', 'Hindi Vyakran', 'Tillu Ji'),
('NCERT', '2', 'Hindi Vyakran', 'Natkhat Diwakar'),
('NCERT', '2', 'Hindi Vyakran', 'Teen Dost'),
('NCERT', '2', 'Hindi Vyakran', 'Duniya Rang-Birangi'),
('NCERT', '2', 'Hindi Vyakran', 'Kaun'),
('NCERT', '2', 'Hindi Vyakran', 'Baingani Jojo'),
('NCERT', '2', 'Hindi Vyakran', 'Tosiya ka Sapna Talaab'),
('NCERT', '2', 'Hindi Vyakran', 'Beej'),
('NCERT', '2', 'Hindi Vyakran', 'Kisaan'),
('NCERT', '2', 'Hindi Vyakran', 'Mooli'),
('NCERT', '2', 'Hindi Vyakran', 'Barsaat aur Mendhak'),
('NCERT', '2', 'Hindi Vyakran', 'Utho Utho'),
('NCERT', '2', 'Hindi Vyakran', 'Sher aur Chuhe ki Dosti'),
('NCERT', '2', 'Hindi Vyakran', 'Out'),
('NCERT', '2', 'Hindi Vyakran', 'Khel Sandhya'),
('NCERT', '2', 'Hindi Vyakran', 'Chhupan-Chhupai'),
('NCERT', '2', 'Hindi Vyakran', 'Haathi Cycle Chala Raha Tha'),
('NCERT', '2', 'Hindi Vyakran', 'Daro Mat!'),
('NCERT', '2', 'Hindi Vyakran', 'Chaar Dishaayein'),
('NCERT', '2', 'Hindi Vyakran', 'Chanda Mama'),
('NCERT', '2', 'Hindi Vyakran', 'Gire Taal Mein Chanda Mama'),
('NCERT', '2', 'Hindi Vyakran', 'Sabse Bada Chhata'),
('NCERT', '2', 'Hindi Vyakran', 'Baadal'),
('NCERT', '2', 'Hindi Vyakran', 'Phir Phurr!'),
('NCERT', '3', 'Maths', 'What’s in a Name?'),
('NCERT', '3', 'Maths', 'Toy Joy'),
('NCERT', '3', 'Maths', 'Double Century'),
('NCERT', '3', 'Maths', 'Vacation with My Nani Maa'),
('NCERT', '3', 'Maths', 'Fun with Shapes'),
('NCERT', '3', 'Maths', 'House of Hundreds– I'),
('NCERT', '3', 'Maths', 'Raksha Bandhan'),
('NCERT', '3', 'Maths', 'Fair Share'),
('NCERT', '3', 'Maths', 'House of Hundreds– II'),
('NCERT', '3', 'Maths', 'Fun at Class Party!'),
('NCERT', '3', 'Maths', 'Filling and Lifting'),
('NCERT', '3', 'Maths', 'Give and Take'),
('NCERT', '3', 'Maths', 'Time Goes On'),
('NCERT', '3', 'Maths', 'The Surajkund Fair'),
('NCERT', '3', 'Maths', 'Learning Material Sheets'),
('NCERT', '3', 'Arts', 'Our National Anthem'),
('NCERT', '3', 'Arts', 'Feel the Rhythm ta ka ta ki Ta'),
('NCERT', '3', 'Arts', 'Travel Around'),
('NCERT', '3', 'Arts', 'Musical Instruments'),
('NCERT', '3', 'Arts', 'Celebratory Notes Let us Dance'),
('NCERT', '3', 'Arts', 'Dance for Joy'),
('NCERT', '3', 'Arts', 'I Play and Dance'),
('NCERT', '3', 'Arts', 'Dance with Nature Explore'),
('NCERT', '3', 'Arts', 'Imagine'),
('NCERT', '3', 'Arts', 'Let’s Create'),
('NCERT', '3', 'Arts', 'Look Around'),
('NCERT', '3', 'Arts', 'Activities'),
('NCERT', '3', 'Arts', 'Integrating All Art Forms'),
('NCERT', '3', 'Arts', 'Objects in Art'),
('NCERT', '3', 'Arts', 'Plants in Art'),
('NCERT', '3', 'Arts', 'Animals in Art'),
('NCERT', '3', 'Arts', 'People Around Us'),
('NCERT', '3', 'Arts', 'Festivals, Occasions, and Celebrations'),
('NCERT', '3', 'English Grammar', 'Colours'),
('NCERT', '3', 'English Grammar', 'Badal and Moti'),
('NCERT', '3', 'English Grammar', 'Best Friends Out in the Garden'),
('NCERT', '3', 'English Grammar', 'Talking Toys'),
('NCERT', '3', 'English Grammar', 'Paper Boats The Big Laddoo'),
('NCERT', '3', 'English Grammar', 'Thank God'),
('NCERT', '3', 'English Grammar', 'Madhu’s Wish Night'),
('NCERT', '3', 'English Grammar', 'Chanda Mama Counts the Stars'),
('NCERT', '3', 'English Grammar', 'Chandrayaan'),
('NCERT', '3', 'Hindi Vyakran', 'Seekho'),
('NCERT', '3', 'Hindi Vyakran', 'Cheenti'),
('NCERT', '3', 'Hindi Vyakran', 'Cheenti aur haathi ki chhupan-chhupai'),
('NCERT', '3', 'Hindi Vyakran', 'Kitne pair?'),
('NCERT', '3', 'Hindi Vyakran', 'Dost ke joote'),
('NCERT', '3', 'Hindi Vyakran', 'Baya hamari chidiya rani!'),
('NCERT', '3', 'Hindi Vyakran', 'Aam ka ped'),
('NCERT', '3', 'Hindi Vyakran', 'Birbal ki khichdi'),
('NCERT', '3', 'Hindi Vyakran', 'Mila ko pata'),
('NCERT', '3', 'Hindi Vyakran', 'Chatur gidad'),
('NCERT', '3', 'Hindi Vyakran', 'Prakriti parv (Phooldei)'),
('NCERT', '3', 'Hindi Vyakran', 'Sano bhai gup-gup'),
('NCERT', '3', 'Hindi Vyakran', 'Rassakashi'),
('NCERT', '3', 'Hindi Vyakran', 'Traffic jam'),
('NCERT', '3', 'Hindi Vyakran', 'Ek jaadui pitara'),
('NCERT', '3', 'Hindi Vyakran', 'Apna-apna kaam'),
('NCERT', '3', 'Hindi Vyakran', 'Pedon ki amma ''Timkka'''),
('NCERT', '3', 'Hindi Vyakran', 'Kisaan ki hoshiyari'),
('NCERT', '3', 'Hindi Vyakran', 'Bharat'),
('NCERT', '3', 'Hindi Vyakran', 'Chandrayaan (samvaad)'),
('NCERT', '3', 'Hindi Vyakran', 'Bolne wali maand'),
('NCERT', '3', 'Hindi Vyakran', 'Hum anek kintu ek'),
('NCERT', '3', 'Hindi Vyakran', 'Hind desh ke nivasi'),
('NCERT', '3', 'Physical Education', 'Throwing and Catching'),
('NCERT', '3', 'Physical Education', 'Kicking and Receiving'),
('NCERT', '3', 'Physical Education', 'Strike the Ball'),
('NCERT', '3', 'Physical Education', 'Little Steps'),
('NCERT', '3', 'Physical Education', 'Local and Traditional Games'),
('NCERT', '3', 'Physical Education', 'Yoga for Daily Life'),
('NCERT', '3', 'Physical Education', 'Yogic Practices (Yoga Sadhana)'),
('NCERT', '3', 'SST', 'Family and Friends'),
('NCERT', '3', 'SST', 'Going to the Mela'),
('NCERT', '3', 'SST', 'Celebrating Festivals'),
('NCERT', '3', 'SST', 'Life Around Us Getting to Know Plants'),
('NCERT', '3', 'SST', 'Plants and Animals Live Together'),
('NCERT', '3', 'SST', 'Living in Harmony'),
('NCERT', '3', 'SST', 'Gifts of Nature Water— A Precious Gift'),
('NCERT', '3', 'SST', 'Food We Eat'),
('NCERT', '3', 'SST', 'Staying Healthy and Happy'),
('NCERT', '3', 'SST', 'Things Around Us This World of Things'),
('NCERT', '3', 'SST', 'Making Things'),
('NCERT', '3', 'SST', 'Taking Charge of Waste'),
('NCERT', '4', 'Maths', 'Shapes Around Us'),
('NCERT', '4', 'Maths', 'Hide and Seek'),
('NCERT', '4', 'Maths', 'Pattern Around Us'),
('NCERT', '4', 'Maths', 'Thousands Around Us'),
('NCERT', '4', 'Maths', 'Sharing and Measuring'),
('NCERT', '4', 'Maths', 'Measuring Length'),
('NCERT', '4', 'Maths', 'The Cleanest Village'),
('NCERT', '4', 'Maths', 'Weigh it, Pour it'),
('NCERT', '4', 'Maths', 'Equal Groups'),
('NCERT', '4', 'Maths', 'Elephants, Tigers, and Leopards'),
('NCERT', '4', 'Maths', 'Fun with Symmetry'),
('NCERT', '4', 'Maths', 'Ticking Clocks and Turning Calendar'),
('NCERT', '4', 'Maths', 'The Transport Museum'),
('NCERT', '4', 'Maths', 'Data Handling'),
('NCERT', '4', 'Arts', 'Arrangements of Objects'),
('NCERT', '4', 'Arts', 'Textures in Nature'),
('NCERT', '4', 'Arts', 'Aqua World'),
('NCERT', '4', 'Arts', 'People in Action'),
('NCERT', '4', 'Arts', 'THEATRE Explore!'),
('NCERT', '4', 'Arts', 'Imagine'),
('NCERT', '4', 'Arts', 'Let’s Create'),
('NCERT', '4', 'Arts', 'Look Around Sing and Play'),
('NCERT', '4', 'Arts', 'Making Music'),
('NCERT', '4', 'Arts', 'Songs and Stories'),
('NCERT', '4', 'Arts', 'Think, Feel, Create'),
('NCERT', '4', 'Arts', 'Sounds and Instruments'),
('NCERT', '4', 'Arts', 'DANCE My Body in Dance'),
('NCERT', '4', 'Arts', 'My Dance Tells Stories'),
('NCERT', '4', 'Arts', 'Creating My Dance'),
('NCERT', '4', 'Arts', 'Emotion and Expression in Dance'),
('NCERT', '4', 'Arts', 'Dances Around Me'),
('NCERT', '4', 'SST', 'Living Together'),
('NCERT', '4', 'SST', 'Exploring Our Neighbourhood'),
('NCERT', '4', 'SST', 'Nature Trail'),
('NCERT', '4', 'SST', 'Growing up with Nature'),
('NCERT', '4', 'SST', 'Food for Health'),
('NCERT', '4', 'SST', 'Happy and Healthy Living'),
('NCERT', '4', 'SST', 'How Things Work'),
('NCERT', '4', 'SST', 'How Things are Made'),
('NCERT', '4', 'SST', 'Different Lands, Different Lives'),
('NCERT', '4', 'SST', 'Our Sky'),
('NCERT', '4', 'English Grammar', 'Together We Can'),
('NCERT', '4', 'English Grammar', 'The Tinkling Bells'),
('NCERT', '4', 'English Grammar', 'Be Smart, Be Safe'),
('NCERT', '4', 'English Grammar', 'One Thing at a Time'),
('NCERT', '4', 'English Grammar', 'The Old Stag'),
('NCERT', '4', 'English Grammar', 'Braille'),
('NCERT', '4', 'English Grammar', 'Fit Body, Fit Mind, Fit Nation'),
('NCERT', '4', 'English Grammar', 'The Lagori Champions'),
('NCERT', '4', 'English Grammar', 'Hekko'),
('NCERT', '4', 'English Grammar', 'The Swing'),
('NCERT', '4', 'English Grammar', 'A Journey to the Magical Mountains'),
('NCERT', '4', 'English Grammar', 'Maheshwar'),
('NCERT', '4', 'Hindi Vyakran', 'Chidiya ka geet'),
('NCERT', '4', 'Hindi Vyakran', 'Mati ki udaan'),
('NCERT', '4', 'Hindi Vyakran', 'Bagiche ka ghongha'),
('NCERT', '4', 'Hindi Vyakran', 'Neem'),
('NCERT', '4', 'Hindi Vyakran', 'Bhaanti-bhaanti ki pattiyan'),
('NCERT', '4', 'Hindi Vyakran', 'Hamara aahar'),
('NCERT', '4', 'Hindi Vyakran', 'Aasman gira'),
('NCERT', '4', 'Hindi Vyakran', 'Cherapunji ke mehmaan'),
('NCERT', '4', 'Hindi Vyakran', 'Jaipur se patra'),
('NCERT', '4', 'Hindi Vyakran', 'Golgappa'),
('NCERT', '4', 'Hindi Vyakran', 'Nakli heere'),
('NCERT', '4', 'Hindi Vyakran', 'Hawa aur dhool'),
('NCERT', '4', 'Hindi Vyakran', 'Onam ke rang'),
('NCERT', '4', 'Hindi Vyakran', 'Mithaiyon ka sammelan'),
('NCERT', '4', 'Hindi Vyakran', 'Jalebi'),
('NCERT', '4', 'Hindi Vyakran', 'Camera'),
('NCERT', '4', 'Hindi Vyakran', 'Sun, imli ke dane sun!'),
('NCERT', '4', 'Hindi Vyakran', 'Thahake'),
('NCERT', '4', 'Hindi Vyakran', 'Kavita ka kamaal'),
('NCERT', '4', 'Hindi Vyakran', 'Shatranj mein maat'),
('NCERT', '4', 'Hindi Vyakran', 'Hamara Aditya'),
('NCERT', '4', 'Hindi Vyakran', 'Hum sab saman ek upvan'),
('NCERT', '5', 'Arts', 'Objects on the Move'),
('NCERT', '5', 'Arts', 'Peeping Out of the Window'),
('NCERT', '5', 'Arts', 'Picturing Stories'),
('NCERT', '5', 'Arts', 'Imaginary Beings'),
('NCERT', '5', 'Arts', 'Spreading the Message'),
('NCERT', '5', 'Arts', 'Create a Scene'),
('NCERT', '5', 'Arts', 'Stitch it for a Story'),
('NCERT', '5', 'Arts', 'Time, Team, Technique'),
('NCERT', '5', 'Arts', 'View and Review'),
('NCERT', '5', 'Arts', 'Sing and Play'),
('NCERT', '5', 'Arts', 'Music Around Me'),
('NCERT', '5', 'Arts', 'Sounds and Instruments'),
('NCERT', '5', 'Arts', 'Building Blocks'),
('NCERT', '5', 'Arts', 'Ideas and Inspiration'),
('NCERT', '5', 'Arts', 'My Everyday Activities in Modes of Dance'),
('NCERT', '5', 'Arts', 'Dancing with Rhythm and Tempos'),
('NCERT', '5', 'Arts', 'Dances of My Nation'),
('NCERT', '5', 'Arts', 'My Dance Expresses Emotions and Narrates Stories'),
('NCERT', '5', 'Arts', 'My Dance and Your Dance'),
('NCERT', '5', 'English Grammar', 'Papa’s Spectacles'),
('NCERT', '5', 'English Grammar', 'Gone with the Scooter'),
('NCERT', '5', 'English Grammar', 'The Rainbow'),
('NCERT', '5', 'English Grammar', 'The Wise Parrot'),
('NCERT', '5', 'English Grammar', 'The Frog'),
('NCERT', '5', 'English Grammar', 'What a Tank!'),
('NCERT', '5', 'English Grammar', 'Gilli Danda'),
('NCERT', '5', 'English Grammar', 'The Decision of the Panchayat'),
('NCERT', '5', 'English Grammar', 'Vocation'),
('NCERT', '5', 'English Grammar', 'Glass Bangles'),
('NCERT', '5', 'Maths', 'We the Travellers—I'),
('NCERT', '5', 'Maths', 'Fractions'),
('NCERT', '5', 'Maths', 'Angles as Turns'),
('NCERT', '5', 'Maths', 'We the Travellers—II'),
('NCERT', '5', 'Maths', 'Far and Near'),
('NCERT', '5', 'Maths', 'The Dairy Farm'),
('NCERT', '5', 'Maths', 'Shapes and Patterns'),
('NCERT', '5', 'Maths', 'Weight and Capacity'),
('NCERT', '5', 'Maths', 'Coconut Farm'),
('NCERT', '5', 'Maths', 'Symmetrical Designs'),
('NCERT', '5', 'Maths', 'Grandmother’s Quilt'),
('NCERT', '5', 'Maths', 'Racing Seconds'),
('NCERT', '5', 'Maths', 'Animal Jumps'),
('NCERT', '5', 'Maths', 'Maps and Locations'),
('NCERT', '5', 'Maths', 'Data Through Pictures'),
('NCERT', '5', 'Physical Education', 'Throwing and Catching'),
('NCERT', '5', 'Physical Education', 'Kicking and Receiving'),
('NCERT', '5', 'Physical Education', 'Strike the Object'),
('NCERT', '5', 'Physical Education', 'Little Steps'),
('NCERT', '5', 'Physical Education', 'Local and Traditional Games'),
('NCERT', '5', 'Physical Education', 'Yoga for Daily Life'),
('NCERT', '5', 'Physical Education', 'Yoga Sadhana'),
('NCERT', '5', 'SST', 'Water—The Essence of Life'),
('NCERT', '5', 'SST', 'Journey of a River'),
('NCERT', '5', 'SST', 'The Mystery of Food'),
('NCERT', '5', 'SST', 'Our School—A Happy Place'),
('NCERT', '5', 'SST', 'Our Vibrant Country'),
('NCERT', '5', 'SST', 'Some Unique Places'),
('NCERT', '5', 'SST', 'Energy—How Things Work'),
('NCERT', '5', 'SST', 'Clothes—How Things are Made'),
('NCERT', '5', 'SST', 'Rhythms of Nature'),
('NCERT', '5', 'SST', 'Earth—Our Shared Home'),
('NCERT', '5', 'Hindi Vyakran', 'Kiran'),
('NCERT', '5', 'Hindi Vyakran', 'Ped ka jadoo'),
('NCERT', '5', 'Hindi Vyakran', 'Nyay ki kusal'),
('NCERT', '5', 'Hindi Vyakran', 'Chand ka kurta'),
('NCERT', '5', 'Hindi Vyakran', 'Jago pyare'),
('NCERT', '5', 'Hindi Vyakran', 'Saanket'),
('NCERT', '5', 'Hindi Vyakran', 'Holi aai, Holi aai'),
('NCERT', '5', 'Hindi Vyakran', 'Saduriyan'),
('NCERT', '5', 'Hindi Vyakran', 'Haathi aur cheenti'),
('NCERT', '5', 'Hindi Vyakran', 'Chatur chitrakar'),
('NCERT', '5', 'Hindi Vyakran', 'Do mendhakon ki yatra'),
('NCERT', '5', 'Hindi Vyakran', 'Mera bachpan'),
('NCERT', '5', 'Hindi Vyakran', 'Kaziranga Rashtriya Udyan ki yatra'),
('NCERT', '5', 'Hindi Vyakran', 'Ghumo-dekho'),
('NCERT', '5', 'Hindi Vyakran', 'Nyay'),
('NCERT', '5', 'Hindi Vyakran', 'Teen machhliyan'),
('NCERT', '5', 'Hindi Vyakran', 'Humare ye kalam mandir'),
('NCERT', '5', 'Hindi Vyakran', 'Ganga ki kahani'),
('NCERT', '5', 'Hindi Vyakran', 'Gaganyaan'),
('NCERT', '6', 'Arts', 'Objects and Still Life'),
('NCERT', '6', 'Arts', 'Changing the Typical Picture'),
('NCERT', '6', 'Arts', 'Portraying People'),
('NCERT', '6', 'Arts', 'Paper Crafts'),
('NCERT', '6', 'Arts', 'Seals to Prints'),
('NCERT', '6', 'Arts', 'Music and your Emotions'),
('NCERT', '6', 'Arts', 'Musical Instruments'),
('NCERT', '6', 'Arts', 'Taal or Talam and Raga or Ragam in Indian Music'),
('NCERT', '6', 'Arts', 'Melodies of Diversity'),
('NCERT', '6', 'Arts', 'Songwriting'),
('NCERT', '6', 'Arts', 'Music and Society'),
('NCERT', '6', 'Arts', 'My Body in Motion'),
('NCERT', '6', 'Arts', 'Breaking Barriers with Dance'),
('NCERT', '6', 'Arts', 'Harmony in Motion'),
('NCERT', '6', 'Arts', 'Dances of Our Land'),
('NCERT', '6', 'Arts', 'Emotions Unveiled'),
('NCERT', '6', 'Arts', 'Let’s Design'),
('NCERT', '6', 'Arts', 'In the Company of Theatre'),
('NCERT', '6', 'Arts', 'Stories of Shadows and Strings — Puppetry'),
('NCERT', '6', 'Arts', 'The Grand Finale'),
('NCERT', '6', 'Arts', 'Integration of All Art Forms'),
('NCERT', '6', 'English Grammar', 'A Bottle of Dew'),
('NCERT', '6', 'English Grammar', 'The Raven and the Fox'),
('NCERT', '6', 'English Grammar', 'Rama to the Rescue'),
('NCERT', '6', 'English Grammar', 'The Unlikely Best Friends'),
('NCERT', '6', 'English Grammar', 'A Friend’s Prayer'),
('NCERT', '6', 'English Grammar', 'The Chair'),
('NCERT', '6', 'English Grammar', 'Neem Baba'),
('NCERT', '6', 'English Grammar', 'What a Bird Thought'),
('NCERT', '6', 'English Grammar', 'Spices that Heal Us'),
('NCERT', '6', 'English Grammar', 'Change of Heart'),
('NCERT', '6', 'English Grammar', 'The Winner'),
('NCERT', '6', 'English Grammar', 'Yoga—A Way of Life'),
('NCERT', '6', 'English Grammar', 'Hamara Bharat—Incredible India!'),
('NCERT', '6', 'English Grammar', 'The Kites'),
('NCERT', '6', 'English Grammar', 'Ila Sachani: Embroidering Dreams with her Feet'),
('NCERT', '6', 'English Grammar', 'National War Memorial'),
('NCERT', '6', 'Maths', 'Patterns in Mathematics'),
('NCERT', '6', 'Maths', 'Lines and Angles'),
('NCERT', '6', 'Maths', 'Number Play'),
('NCERT', '6', 'Maths', 'Data Handling and Presentation'),
('NCERT', '6', 'Maths', 'Prime Time'),
('NCERT', '6', 'Maths', 'Perimeter and Area'),
('NCERT', '6', 'Maths', 'Fractions'),
('NCERT', '6', 'Maths', 'Playing with Constructions'),
('NCERT', '6', 'Maths', 'Symmetry'),
('NCERT', '6', 'Maths', 'The Other Side of Zero'),
('NCERT', '6', 'Physical Education', 'Ice Water'),
('NCERT', '6', 'Physical Education', 'Seven Stones'),
('NCERT', '6', 'Physical Education', 'Aerobic Exercises'),
('NCERT', '6', 'Physical Education', 'Follow Me'),
('NCERT', '6', 'Physical Education', 'Number Game'),
('NCERT', '6', 'Physical Education', 'Hula Hoop Jump'),
('NCERT', '6', 'Physical Education', 'Obstacle Race'),
('NCERT', '6', 'Physical Education', 'Balancing Act'),
('NCERT', '6', 'Physical Education', 'Shivam Says'),
('NCERT', '6', 'Physical Education', 'Collaborate and Conquer'),
('NCERT', '6', 'Physical Education', 'Grab the Ball'),
('NCERT', '6', 'Physical Education', 'Push-up Position and Pass the Ball'),
('NCERT', '6', 'Physical Education', 'Tic-Tac-Toe Dribble Relay'),
('NCERT', '6', 'Physical Education', 'Crocodile Race'),
('NCERT', '6', 'Physical Education', 'Head, Shoulder, Knee and Ball'),
('NCERT', '6', 'Physical Education', 'Sitting'),
('NCERT', '6', 'Physical Education', 'Chasing'),
('NCERT', '6', 'Physical Education', 'Giving Kho'),
('NCERT', '6', 'Physical Education', 'Running on a Straight Line'),
('NCERT', '6', 'Physical Education', 'Dodging'),
('NCERT', '6', 'Physical Education', 'Zig-Zag Running'),
('NCERT', '6', 'Physical Education', 'Pole Turn'),
('NCERT', '6', 'Physical Education', 'Covering Chase'),
('NCERT', '6', 'Physical Education', 'Chain'),
('NCERT', '6', 'Physical Education', 'Fake Kho'),
('NCERT', '6', 'Physical Education', 'Pole Dive'),
('NCERT', '6', 'Physical Education', 'Toe Tapping'),
('NCERT', '6', 'Physical Education', '3-2-3 Chain'),
('NCERT', '6', 'Physical Education', 'Passing'),
('NCERT', '6', 'Physical Education', 'Catching'),
('NCERT', '6', 'Physical Education', '10-pass'),
('NCERT', '6', 'Physical Education', 'Dribbling'),
('NCERT', '6', 'Physical Education', 'Obstacle Dribbling'),
('NCERT', '6', 'Physical Education', 'Shoot the Ball'),
('NCERT', '6', 'Physical Education', 'Dodge Ball'),
('NCERT', '6', 'Physical Education', 'Dribble and Shoot'),
('NCERT', '6', 'Physical Education', 'Pass and Shoot'),
('NCERT', '6', 'Physical Education', 'Shootout Tournament'),
('NCERT', '6', 'Physical Education', 'Goalkeeper’s Defensive Skills'),
('NCERT', '6', 'Physical Education', 'Blocking'),
('NCERT', '6', 'Physical Education', 'Assimilation'),
('NCERT', '6', 'Physical Education', 'Yoga for Daily Life'),
('NCERT', '6', 'Physical Education', 'Preparing for Yogic Practices'),
('NCERT', '6', 'Physical Education', 'Āsanas'),
('NCERT', '6', 'Physical Education', 'Prānāyāma'),
('NCERT', '6', 'Physical Education', 'Dhārana, Dhyāna, and Samādhi'),
('NCERT', '6', 'Physical Education', 'Krīdā Yoga'),
('NCERT', '6', 'Science', 'The Wonderful World of Science'),
('NCERT', '6', 'Science', 'Diversity in the Living World'),
('NCERT', '6', 'Science', 'Mindful Eating: A Path to a Healthy Body'),
('NCERT', '6', 'Science', 'Exploring Magnets'),
('NCERT', '6', 'Science', 'Measurement of Length and Motion'),
('NCERT', '6', 'Science', 'Materials Around Us'),
('NCERT', '6', 'Science', 'Temperature and its Measurement'),
('NCERT', '6', 'Science', 'A Journey through States of Water'),
('NCERT', '6', 'Science', 'Methods of Separation in Everyday Life'),
('NCERT', '6', 'Science', 'Living Creatures: Exploring their Characteristics'),
('NCERT', '6', 'Science', 'Nature’s Treasures'),
('NCERT', '6', 'Science', 'Beyond Earth'),
('NCERT', '6', 'SST', 'Locating Places on the Earth'),
('NCERT', '6', 'SST', 'Oceans and Continents'),
('NCERT', '6', 'SST', 'Landforms and Life'),
('NCERT', '6', 'SST', 'Timeline and Sources of History'),
('NCERT', '6', 'SST', 'India, That Is Bharat'),
('NCERT', '6', 'SST', 'The Beginnings of Indian Civilisation'),
('NCERT', '6', 'SST', 'India''s Cultural Roots'),
('NCERT', '6', 'SST', 'Unity in Diversity, or Many in the One'),
('NCERT', '6', 'SST', 'Family and Community'),
('NCERT', '6', 'SST', 'Grassroots Democracy — Governance'),
('NCERT', '6', 'SST', 'Grassroots Democracy — Local Government in Rural Areas'),
('NCERT', '6', 'SST', 'Grassroots Democracy — Local Government in Urban Areas'),
('NCERT', '6', 'SST', 'The Value of Work'),
('NCERT', '6', 'SST', 'Economic Activities Around Us'),
('NCERT', '6', 'Vocational Education', 'School Kitchen Garden'),
('NCERT', '6', 'Vocational Education', 'Biodiversity Register'),
('NCERT', '6', 'Vocational Education', 'Work with Machines and Materials'),
('NCERT', '6', 'Vocational Education', 'Maker Skills'),
('NCERT', '6', 'Vocational Education', 'Animation and Games'),
('NCERT', '6', 'Vocational Education', 'School Museum'),
('NCERT', '6', 'Vocational Education', 'Cooking without Fire'),
('NCERT', '6', 'Hindi Vyakran', 'Maatbhumi'),
('NCERT', '6', 'Hindi Vyakran', 'Pushp ki abhilasha'),
('NCERT', '6', 'Hindi Vyakran', 'Gol'),
('NCERT', '6', 'Hindi Vyakran', 'Ek daud aisi bhi'),
('NCERT', '6', 'Hindi Vyakran', 'Pehli bund'),
('NCERT', '6', 'Hindi Vyakran', 'Haar ki jeet'),
('NCERT', '6', 'Hindi Vyakran', 'Raheem ke dohe'),
('NCERT', '6', 'Hindi Vyakran', 'Meri maa'),
('NCERT', '6', 'Hindi Vyakran', 'Jalate chalo'),
('NCERT', '6', 'Hindi Vyakran', 'Sattriya aur Bihu nritya'),
('NCERT', '6', 'Hindi Vyakran', 'Maiya main nahi makhan khayo'),
('NCERT', '6', 'Hindi Vyakran', 'Pariksha'),
('NCERT', '6', 'Hindi Vyakran', 'Chetak ki veerta'),
('NCERT', '6', 'Hindi Vyakran', 'Hind Mahasagar mein chhota-sa Hindustan'),
('NCERT', '6', 'Hindi Vyakran', 'Ped ki baat'),
('NCERT', '6', 'Hindi Vyakran', 'Aao bachcho tumhe dikhaye jhanki Hindustan ki'),
('NCERT', '6', 'sanskrit', 'Vayam varnamalam pathamah'),
('NCERT', '6', 'sanskrit', 'Sanyukt-vyanjanani'),
('NCERT', '6', 'sanskrit', 'Eshah kah? Esha ka? Etat kim?'),
('NCERT', '6', 'sanskrit', 'Aham cha tvam cha'),
('NCERT', '6', 'sanskrit', 'Sankhyaganana'),
('NCERT', '6', 'sanskrit', 'Aham pratah utishthami'),
('NCERT', '6', 'sanskrit', 'Shoorah vayam dheerah vayam'),
('NCERT', '6', 'sanskrit', 'Sah eva mahan chitrakarah'),
('NCERT', '6', 'sanskrit', 'Atithidevo bhava'),
('NCERT', '6', 'sanskrit', 'Buddhih sarvarthasadhika'),
('NCERT', '6', 'sanskrit', 'Yah janati sah panditah'),
('NCERT', '6', 'sanskrit', 'Tvam aapanam gachchha'),
('NCERT', '6', 'sanskrit', 'Prithivyam trini ratnani'),
('NCERT', '6', 'sanskrit', 'Alasyam hi manushyanam sharirasthah mahan ripuh'),
('NCERT', '6', 'sanskrit', 'Madhavasya priyam angam'),
('NCERT', '6', 'sanskrit', 'Vrikshah satpurushah iva'),
('NCERT', '7', 'Arts', 'Understanding Emotions'),
('NCERT', '7', 'Arts', 'Say More without Speech—Mime'),
('NCERT', '7', 'Arts', 'Let’s Design—Stage Technicals'),
('NCERT', '7', 'Arts', 'Story of India’s Storytelling Tradition'),
('NCERT', '7', 'Arts', 'Making Music'),
('NCERT', '7', 'Arts', 'Music, Emotions and Creativity'),
('NCERT', '7', 'Arts', 'Ragas and Talas/Taal'),
('NCERT', '7', 'Arts', 'The Music of the People'),
('NCERT', '7', 'Arts', 'Performance'),
('NCERT', '7', 'Arts', 'Dance Vocabulary and Techniques'),
('NCERT', '7', 'Arts', 'Dance, You and Creativity'),
('NCERT', '7', 'Arts', 'Personalities'),
('NCERT', '7', 'Arts', 'Natya'),
('NCERT', '7', 'Arts', 'Objects in Icons and Symbols'),
('NCERT', '7', 'Arts', 'Nature’s Palette'),
('NCERT', '7', 'Arts', 'How You Feel'),
('NCERT', '7', 'Arts', 'Textiles and Traditions'),
('NCERT', '7', 'Arts', 'The Art of Calligraphy'),
('NCERT', '7', 'Arts', 'Integration of All Art Forms—Sculptures Come Alive'),
('NCERT', '7', 'English Grammar', 'The Day the River Spoke'),
('NCERT', '7', 'English Grammar', 'Try Again'),
('NCERT', '7', 'English Grammar', 'Three Days to See'),
('NCERT', '7', 'English Grammar', 'Animals, Birds, and Dr. Dolittle'),
('NCERT', '7', 'English Grammar', 'A Funny Man'),
('NCERT', '7', 'English Grammar', 'Say the Right Thing'),
('NCERT', '7', 'English Grammar', 'My Brother’s Great Invention'),
('NCERT', '7', 'English Grammar', 'Paper Boats'),
('NCERT', '7', 'English Grammar', 'North, South, East, West'),
('NCERT', '7', 'English Grammar', 'The Tunnel'),
('NCERT', '7', 'English Grammar', 'Travel'),
('NCERT', '7', 'English Grammar', 'Conquering the Summit'),
('NCERT', '7', 'English Grammar', 'A Homage to Our Brave Soldiers'),
('NCERT', '7', 'English Grammar', 'My Dear Soldiers'),
('NCERT', '7', 'English Grammar', 'Rani Abbakka'),
('NCERT', '7', 'Maths', 'Large Numbers Around Us'),
('NCERT', '7', 'Maths', 'Arithmetic Expressions'),
('NCERT', '7', 'Maths', 'A Peek Beyond the Point'),
('NCERT', '7', 'Maths', 'Expressions using Letter-Numbers'),
('NCERT', '7', 'Maths', 'Parallel and Intersecting Lines'),
('NCERT', '7', 'Maths', 'Number Play'),
('NCERT', '7', 'Maths', 'A Tale of Three Intersecting Lines'),
('NCERT', '7', 'Maths', 'Working with Fractions'),
('NCERT', '7', 'Maths', 'Geometric Twins'),
('NCERT', '7', 'Maths', 'Operations with Integers'),
('NCERT', '7', 'Maths', 'Finding Common Ground'),
('NCERT', '7', 'Maths', 'Another Peek Beyond the Point'),
('NCERT', '7', 'Maths', 'Connecting the Dots'),
('NCERT', '7', 'Maths', 'Constructions and Tilings'),
('NCERT', '7', 'Maths', 'Finding the Unknown'),
('NCERT', '7', 'Physical Education', 'The Ball Progression Game'),
('NCERT', '7', 'Physical Education', 'Ghorpadiche Shepoot'),
('NCERT', '7', 'Physical Education', 'Nalugu Rallu Ata'),
('NCERT', '7', 'Physical Education', 'Gidhada Gudkavan'),
('NCERT', '7', 'Physical Education', 'Stand Up, Speak Out'),
('NCERT', '7', 'Physical Education', 'Harassment Prevention Skit'),
('NCERT', '7', 'Physical Education', 'Set It Up, Knock It Down'),
('NCERT', '7', 'Physical Education', 'Dhaan Ki Bori'),
('NCERT', '7', 'Physical Education', 'Caterpillar Race'),
('NCERT', '7', 'Physical Education', 'Count and Connect Game'),
('NCERT', '7', 'Physical Education', 'Skipping Race'),
('NCERT', '7', 'Physical Education', 'Atya-patya'),
('NCERT', '7', 'Physical Education', 'Food for Health'),
('NCERT', '7', 'Physical Education', 'Dapo Nyarka Sunam'),
('NCERT', '7', 'Physical Education', 'Madhu and Manu'),
('NCERT', '7', 'Physical Education', 'Skipping Song'),
('NCERT', '7', 'Physical Education', 'Forehand Grip and Air Toss'),
('NCERT', '7', 'Physical Education', 'Backhand Grip and Air Toss'),
('NCERT', '7', 'Physical Education', 'Footwork Skills'),
('NCERT', '7', 'Physical Education', 'Backhand Low Serve'),
('NCERT', '7', 'Physical Education', 'Backhand Lift'),
('NCERT', '7', 'Physical Education', 'Forehand Lift'),
('NCERT', '7', 'Physical Education', 'Forehand High Serve'),
('NCERT', '7', 'Physical Education', 'Forehand Low Serve'),
('NCERT', '7', 'Physical Education', 'Forehand Drive'),
('NCERT', '7', 'Physical Education', 'Backhand Drive'),
('NCERT', '7', 'Physical Education', 'Forehand Clear'),
('NCERT', '7', 'Physical Education', 'Forehand Drop'),
('NCERT', '7', 'Physical Education', 'Badminton Match'),
('NCERT', '7', 'Physical Education', 'Kicking the Ball with the Inside of the Foot'),
('NCERT', '7', 'Physical Education', 'Receiving the Ball by Inside of the Foot'),
('NCERT', '7', 'Physical Education', 'Passing the Rolling Ball'),
('NCERT', '7', 'Physical Education', 'Step Trapping'),
('NCERT', '7', 'Physical Education', 'Dribble'),
('NCERT', '7', 'Physical Education', 'Feinting'),
('NCERT', '7', 'Physical Education', 'Kicking the Ball for Accuracy'),
('NCERT', '7', 'Physical Education', 'Passing the Ball in the Air'),
('NCERT', '7', 'Physical Education', 'Pass and Move Relay Drill'),
('NCERT', '7', 'Physical Education', 'Interception'),
('NCERT', '7', 'Physical Education', 'Front Block Tackling'),
('NCERT', '7', 'Physical Education', 'Goal Keeping'),
('NCERT', '7', 'Physical Education', '5-a-side Match'),
('NCERT', '7', 'Physical Education', 'Raiding Foot Work'),
('NCERT', '7', 'Physical Education', 'Hand Touch'),
('NCERT', '7', 'Physical Education', 'Toe Touch'),
('NCERT', '7', 'Physical Education', 'Kick'),
('NCERT', '7', 'Physical Education', 'Ankle-hold'),
('NCERT', '7', 'Physical Education', 'Thigh-hold'),
('NCERT', '7', 'Physical Education', 'Knee-hold'),
('NCERT', '7', 'Physical Education', 'Wrist-hold'),
('NCERT', '7', 'Physical Education', 'Waist-hold'),
('NCERT', '7', 'Physical Education', 'Chain-hold'),
('NCERT', '7', 'Physical Education', 'Yoga for Daily Life'),
('NCERT', '7', 'Physical Education', 'Yoga Sadhana'),
('NCERT', '7', 'Physical Education', 'Āsana'),
('NCERT', '7', 'Physical Education', 'Prānāyāma'),
('NCERT', '7', 'Science', 'The Ever-Evolving World of Science'),
('NCERT', '7', 'Science', 'Exploring Substances: Acidic, Basic, and Neutral'),
('NCERT', '7', 'Science', 'Electricity: Circuits and their Components'),
('NCERT', '7', 'Science', 'The World of Metals and Non-metals'),
('NCERT', '7', 'Science', 'Changes Around Us: Physical and Chemical'),
('NCERT', '7', 'Science', 'Adolescence: A Stage of Growth and Change'),
('NCERT', '7', 'Science', 'Heat Transfer in Nature'),
('NCERT', '7', 'Science', 'Measurement of Time and Motion'),
('NCERT', '7', 'Science', 'Life Processes in Animals'),
('NCERT', '7', 'Science', 'Life Processes in Plants'),
('NCERT', '7', 'Science', 'Light: Shadows and Reflections'),
('NCERT', '7', 'Science', 'Earth, Moon, and the Sun'),
('NCERT', '7', 'SST', 'Geographical Diversity of India'),
('NCERT', '7', 'SST', 'Understanding the Weather'),
('NCERT', '7', 'SST', 'Climates of India'),
('NCERT', '7', 'SST', 'New Beginnings: Cities and States'),
('NCERT', '7', 'SST', 'The Rise of Empires'),
('NCERT', '7', 'SST', 'The Age of Reorganisation'),
('NCERT', '7', 'SST', 'The Gupta Era: An Age of Tireless Creativity'),
('NCERT', '7', 'SST', 'How the Land Becomes Sacred'),
('NCERT', '7', 'SST', 'From the Rulers to the Ruled: Types of Governments'),
('NCERT', '7', 'SST', 'The Constitution of India — An Introduction'),
('NCERT', '7', 'SST', 'From Barter to Money'),
('NCERT', '7', 'SST', 'Understanding Markets'),
('NCERT', '7', 'SST', 'Political Map of India'),
('NCERT', '7', 'SST', 'Physical Map of India'),
('NCERT', '7', 'SST', 'The Story of Indian Farming'),
('NCERT', '7', 'SST', 'India and Her Neighbours'),
('NCERT', '7', 'SST', 'Empires and Kingdoms: 6th to 10th Centuries'),
('NCERT', '7', 'SST', 'Turning Tides: 11th and 12th Centuries'),
('NCERT', '7', 'SST', 'India, a Home to Many'),
('NCERT', '7', 'SST', 'The State, the Government, and You'),
('NCERT', '7', 'SST', 'Infrastructure: Engine of India’s Development'),
('NCERT', '7', 'SST', 'Banks and the Magic of Finance'),
('NCERT', '7', 'Vocational Education', 'Plant Nursery'),
('NCERT', '7', 'Vocational Education', 'School Habitat Garden'),
('NCERT', '7', 'Vocational Education', 'Work with Machines and Materials'),
('NCERT', '7', 'Vocational Education', 'Tie and Dye'),
('NCERT', '7', 'Vocational Education', 'AI Assistant'),
('NCERT', '7', 'Vocational Education', 'Storytime with Puppets'),
('NCERT', '7', 'Vocational Education', 'Family Health Handbook'),
('NCERT', '7', 'Hindi Vyakran', 'Maan, kah ek kahani'),
('NCERT', '7', 'Hindi Vyakran', 'Teen buddhimaan'),
('NCERT', '7', 'Hindi Vyakran', 'Phool aur kaanta'),
('NCERT', '7', 'Hindi Vyakran', 'Paani re paani'),
('NCERT', '7', 'Hindi Vyakran', 'Nahi hona beemar'),
('NCERT', '7', 'Hindi Vyakran', 'Giridhar Kavirai ka kundaliya'),
('NCERT', '7', 'Hindi Vyakran', 'Varsha-bahar'),
('NCERT', '7', 'Hindi Vyakran', 'Birju Maharaj se sakshatkar'),
('NCERT', '7', 'Hindi Vyakran', 'Natyaganan sandhi'),
('NCERT', '7', 'Hindi Vyakran', 'Dheediya'),
('NCERT', '7', 'Hindi Vyakran', 'Meera ke pad'),
('NCERT', '7', 'sanskrit', 'Vande Bharat Matram'),
('NCERT', '7', 'sanskrit', 'Nityam pibamah subhashita rasam'),
('NCERT', '7', 'sanskrit', 'Mitraya namah'),
('NCERT', '7', 'sanskrit', 'Na labhyate chet amlam draksha phalam'),
('NCERT', '7', 'sanskrit', 'Seva hi paramo dharmah'),
('NCERT', '7', 'sanskrit', 'Kridama vayam shlokantyaksheem'),
('NCERT', '7', 'sanskrit', 'Ishavasya midam sarvam'),
('NCERT', '7', 'sanskrit', 'Hitam manohari cha durlabham vachah'),
('NCERT', '7', 'sanskrit', 'Annad bhavanti bhutani'),
('NCERT', '7', 'sanskrit', 'Dashamah kah?'),
('NCERT', '7', 'sanskrit', 'Dweepeshu ramyah dweepo andamanah'),
('NCERT', '7', 'sanskrit', 'Veerangana Pannadhaya'),
('NCERT', '8', 'Arts', 'Bringing Words Alive—Play Reading'),
('NCERT', '8', 'Arts', 'One Stage, Many Scripts'),
('NCERT', '8', 'Arts', 'From Page to Stage'),
('NCERT', '8', 'Arts', 'Applause and Advice'),
('NCERT', '8', 'Arts', 'Discovering the Elements of Music'),
('NCERT', '8', 'Arts', 'Musical Instruments'),
('NCERT', '8', 'Arts', 'Indian Classical Music'),
('NCERT', '8', 'Arts', 'Inspiration and Imagination'),
('NCERT', '8', 'Arts', 'My World of Music'),
('NCERT', '8', 'Arts', 'Inner Dynamics of Dance'),
('NCERT', '8', 'Arts', 'Pan Indian Dance Forms'),
('NCERT', '8', 'Arts', 'Dance for Well-being'),
('NCERT', '8', 'Arts', 'Innovation, Inclusivity and Inspiring Change'),
('NCERT', '8', 'Arts', 'A Presentation of Dance and Choreography'),
('NCERT', '8', 'Arts', 'Elements and Principles of Visual Art and Design'),
('NCERT', '8', 'Arts', 'Still Life in Colour'),
('NCERT', '8', 'Arts', 'People in Places'),
('NCERT', '8', 'Arts', 'Arts of the People, With the People, For the People'),
('NCERT', '8', 'Arts', 'Campaign for Art Awareness'),
('NCERT', '8', 'English Grammar', 'The Wit that Won Hearts'),
('NCERT', '8', 'English Grammar', 'A Concrete Example'),
('NCERT', '8', 'English Grammar', 'Wisdom Paves the Way'),
('NCERT', '8', 'English Grammar', 'A Tale of Valour: Major Somnath Sharma and the Battle of Badgam'),
('NCERT', '8', 'English Grammar', 'Somebody’s Mother'),
('NCERT', '8', 'English Grammar', 'Verghese Kurien—I Too Had A Dream'),
('NCERT', '8', 'English Grammar', 'The Case of the Fifth Word'),
('NCERT', '8', 'English Grammar', 'The Magic Brush of Dreams'),
('NCERT', '8', 'English Grammar', 'Spectacular Wonders'),
('NCERT', '8', 'English Grammar', 'The Cherry Tree'),
('NCERT', '8', 'English Grammar', 'Harvest Hymn'),
('NCERT', '8', 'English Grammar', 'Waiting for the Rain'),
('NCERT', '8', 'English Grammar', 'Feathered Friend'),
('NCERT', '8', 'English Grammar', 'Magnifying Glass'),
('NCERT', '8', 'English Grammar', 'Bibha Chowdhuri: The Beam of Light that Lit the Path for Women in Indian Science'),
('NCERT', '8', 'Maths', 'A Square and A Cube'),
('NCERT', '8', 'Maths', 'Power Play'),
('NCERT', '8', 'Maths', 'A Story of Numbers'),
('NCERT', '8', 'Maths', 'Quadrilaterals'),
('NCERT', '8', 'Maths', 'Number Play'),
('NCERT', '8', 'Maths', 'We Distribute, Yet Things Multiply'),
('NCERT', '8', 'Maths', 'Proportional Reasoning-1'),
('NCERT', '8', 'Maths', 'Fractions in Disguise'),
('NCERT', '8', 'Maths', 'The Baudhayana-Pythagoras Theorem'),
('NCERT', '8', 'Maths', 'Proportional Reasoning-2'),
('NCERT', '8', 'Maths', 'Exploring Some Geometric Themes'),
('NCERT', '8', 'Maths', 'Tales by Dots and Lines'),
('NCERT', '8', 'Maths', 'Algebra Play'),
('NCERT', '8', 'Maths', 'Area'),
('NCERT', '8', 'Physical Education', 'Horse Vault Race'),
('NCERT', '8', 'Physical Education', 'Progressive Mass Drill'),
('NCERT', '8', 'Physical Education', 'Baraf Pānī'),
('NCERT', '8', 'Physical Education', 'Chār Tālī'),
('NCERT', '8', 'Physical Education', 'Conduction Relay'),
('NCERT', '8', 'Physical Education', 'Motion-in-Action Relay'),
('NCERT', '8', 'Physical Education', 'Breathing in Action'),
('NCERT', '8', 'Physical Education', 'Flex and React Challenge'),
('NCERT', '8', 'Physical Education', 'Move Like a Machine'),
('NCERT', '8', 'Physical Education', 'Adapt and Achieve'),
('NCERT', '8', 'Physical Education', 'Crawl to the Front'),
('NCERT', '8', 'Physical Education', 'Rock-Paper-Championship Run'),
('NCERT', '8', 'Physical Education', 'Modified Triathlon Activity'),
('NCERT', '8', 'Physical Education', 'Pass, Sit, and Score'),
('NCERT', '8', 'Physical Education', 'Crab Crawl Ball Relay'),
('NCERT', '8', 'Physical Education', 'Hitting Running Target Game'),
('NCERT', '8', 'Physical Education', 'Kick Volleyball'),
('NCERT', '8', 'Physical Education', 'Ropeless Tug of War'),
('NCERT', '8', 'Physical Education', 'Swāsthya Dauḍ'),
('NCERT', '8', 'Physical Education', 'Crouch or Sitting Start'),
('NCERT', '8', 'Physical Education', 'Chase and Tag'),
('NCERT', '8', 'Physical Education', 'Reaction Game'),
('NCERT', '8', 'Physical Education', 'Long Jump'),
('NCERT', '8', 'Physical Education', 'Standing Broad Jump'),
('NCERT', '8', 'Physical Education', 'Hopping'),
('NCERT', '8', 'Physical Education', 'Making an Arch'),
('NCERT', '8', 'Physical Education', 'Landing'),
('NCERT', '8', 'Physical Education', 'High Jump'),
('NCERT', '8', 'Physical Education', 'Heading Suspended Ball'),
('NCERT', '8', 'Physical Education', 'Trikoṇa Kainchī Kūda'),
('NCERT', '8', 'Physical Education', 'Putting Ball'),
('NCERT', '8', 'Physical Education', 'Grip'),
('NCERT', '8', 'Physical Education', 'Footwork'),
('NCERT', '8', 'Physical Education', 'Forehand Push'),
('NCERT', '8', 'Physical Education', 'Backhand Push'),
('NCERT', '8', 'Physical Education', 'Basic Service'),
('NCERT', '8', 'Physical Education', 'Topspin Service'),
('NCERT', '8', 'Physical Education', 'Backspin Service'),
('NCERT', '8', 'Physical Education', 'Forehand Drive'),
('NCERT', '8', 'Physical Education', 'Backhand Drive'),
('NCERT', '8', 'Physical Education', 'Forehand Topspin'),
('NCERT', '8', 'Physical Education', 'Backhand Topspin'),
('NCERT', '8', 'Physical Education', 'Smash'),
('NCERT', '8', 'Physical Education', 'Table Tennis Game'),
('NCERT', '8', 'Physical Education', 'Underhand Pass'),
('NCERT', '8', 'Physical Education', 'Overhead Pass'),
('NCERT', '8', 'Physical Education', 'Underhand Serve'),
('NCERT', '8', 'Physical Education', 'Overhead Serve'),
('NCERT', '8', 'Physical Education', 'Setting'),
('NCERT', '8', 'Physical Education', 'Spike'),
('NCERT', '8', 'Physical Education', 'Block'),
('NCERT', '8', 'Physical Education', 'Dig'),
('NCERT', '8', 'Physical Education', 'Ball Rotation Activity'),
('NCERT', '8', 'Physical Education', 'Ace Accuracy Contest'),
('NCERT', '8', 'Physical Education', 'Ball Throw Activity'),
('NCERT', '8', 'Physical Education', '11-Point Match'),
('NCERT', '8', 'Physical Education', 'Yoga for Daily Life'),
('NCERT', '8', 'Physical Education', 'Yoga Sādhanā'),
('NCERT', '8', 'Physical Education', 'Āsanā'),
('NCERT', '8', 'Physical Education', 'Prānāyāma'),
('NCERT', '8', 'Science', 'Exploring the Investigative World of Science'),
('NCERT', '8', 'Science', 'The Invisible Living World: Beyond Our Naked Eye'),
('NCERT', '8', 'Science', 'Health: The Ultimate Treasure'),
('NCERT', '8', 'Science', 'Electricity: Magnetic and Heating Effects'),
('NCERT', '8', 'Science', 'Exploring Forces'),
('NCERT', '8', 'Science', 'Pressure, Winds, Storms, and Cyclones'),
('NCERT', '8', 'Science', 'Particulate Nature of Matter'),
('NCERT', '8', 'Science', 'Nature of Matter: Elements, Compounds, and Mixtures'),
('NCERT', '8', 'Science', 'The Amazing World of Solutes, Solvents, and Solutions'),
('NCERT', '8', 'Science', 'Light: Mirrors and Lenses'),
('NCERT', '8', 'Science', 'Keeping Time with the Skies'),
('NCERT', '8', 'Science', 'How Nature Works in Harmony'),
('NCERT', '8', 'Science', 'Our Home: Earth, a Unique Life Sustaining Planet'),
('NCERT', '8', 'SST', 'Natural Resources and Their Use'),
('NCERT', '8', 'SST', 'A Note on History’s Darker Periods'),
('NCERT', '8', 'SST', 'Reshaping India’s Political Map'),
('NCERT', '8', 'SST', 'The Rise of the Marathas'),
('NCERT', '8', 'SST', 'The Colonial Era in India'),
('NCERT', '8', 'SST', 'Universal Franchise and India’s Electoral System'),
('NCERT', '8', 'SST', 'The Parliamentary System: Legislature and Executive'),
('NCERT', '8', 'SST', 'Factors of Production'),
('NCERT', '8', 'Vocational Education', 'Hydroponics: Growing Plants without Soil'),
('NCERT', '8', 'Vocational Education', 'Feeding and Caring for Farm Animals'),
('NCERT', '8', 'Vocational Education', 'Working with Wood and Bamboo'),
('NCERT', '8', 'Vocational Education', 'Home Automation'),
('NCERT', '8', 'Vocational Education', 'Water Audit for Water Management'),
('NCERT', '8', 'Vocational Education', 'Creating Advertisements'),
('NCERT', '8', 'Hindi Vyakran', 'Swadesh'),
('NCERT', '8', 'Hindi Vyakran', 'Do gauraiya'),
('NCERT', '8', 'Hindi Vyakran', 'Mitralaabh'),
('NCERT', '8', 'Hindi Vyakran', 'Ek aashirvaad'),
('NCERT', '8', 'Hindi Vyakran', 'Haridwar'),
('NCERT', '8', 'Hindi Vyakran', 'Kabir ke dohe'),
('NCERT', '8', 'Hindi Vyakran', 'Kadam milakar chalna hoga'),
('NCERT', '8', 'Hindi Vyakran', 'Ek tokri bhar mitti'),
('NCERT', '8', 'Hindi Vyakran', 'Mat baandho'),
('NCERT', '8', 'Hindi Vyakran', 'Naye mehmaan'),
('NCERT', '8', 'Hindi Vyakran', 'Aadmi ka anupaat'),
('NCERT', '8', 'Hindi Vyakran', 'Tarun ke swapn'),
('NCERT', '8', 'sanskrit', 'Sangachchhadhvam samvadadhvam'),
('NCERT', '8', 'sanskrit', 'Alpanamapi vastunam samhatih karyasadhika'),
('NCERT', '8', 'sanskrit', 'Subhashitarasam peetva jeevanam saphalam kuru'),
('NCERT', '8', 'sanskrit', 'Pranamyo deshbhakto''yam Gopabandhurmahamanah'),
('NCERT', '8', 'sanskrit', 'Gita sugita kartavya'),
('NCERT', '8', 'sanskrit', 'Digi Bharatam yugaparivartanam'),
('NCERT', '8', 'sanskrit', 'Manjulamanjusha sundarasurabhasha'),
('NCERT', '8', 'sanskrit', 'Pashyata konam aishanyam Bharatasya manoharam'),
('NCERT', '8', 'sanskrit', 'Ko''ruk? Ko''ruk? Ko''ruk?'),
('NCERT', '8', 'sanskrit', 'Sannimitte varam tyagah (part 1)'),
('NCERT', '8', 'sanskrit', 'Sannimitte varam tyagah (part 2)'),
('NCERT', '8', 'sanskrit', 'Samyag varna prayogena brahmaloke mahiyate'),
('NCERT', '8', 'sanskrit', 'Varnoccharan shiksha');